### ISSUE TITLE
Photon controller install fails with timeout

### ISSUE THREAD

**Issue by govint** [vmware/photon-controller#111]
Installed the installer OVA and ran photon-setup platform with a configuration (see below). Setup fails with a timeout in trying to install the Photon controller.

2017-04-28 08:28:01 INFO  Installing Lightwave
2017-04-28 08:28:01 INFO  Install Lightwave Controller at lightwave-1
2017-04-28 08:28:21 INFO  Info: Lightwave does not exist at the specified IP address. Deploying new Lightwave OVA
2017-04-28 08:28:21 INFO  Start [Task: Lightwave Installation]
2017-04-28 08:28:21 INFO  Info [Task: Lightwave Installation] : Deploying and powering on the Lightwave VM on ESXi host: 10.110.48.56
2017-04-28 08:28:21 INFO  Info: Deploying and powering on the Lightwave VM on ESXi host: 10.110.48.56
2017-04-28 08:28:21 INFO  Info [Task: Lightwave Installation] : Starting appliance deployment
2017-04-28 08:28:34 INFO  Progress [Task: Lightwave Installation]: 20%
2017-04-28 08:28:38 INFO  Progress [Task: Lightwave Installation]: 40%
2017-04-28 08:28:46 INFO  Progress [Task: Lightwave Installation]: 80%
2017-04-28 08:28:50 INFO  Progress [Task: Lightwave Installation]: 0%
2017-04-28 08:28:51 INFO  Stop [Task: Lightwave Installation]
2017-04-28 08:29:39 INFO  Info: Lightwave already exists. Skipping deployment of lightwave.
2017-04-28 08:29:39 INFO  COMPLETE: Install Lightwave Controller
2017-04-28 08:29:39 INFO  Installing Photon Controller Cluster
2017-04-28 08:29:39 INFO  Info: Installing the Photon Controller Cluster
2017-04-28 08:29:39 INFO  Info: Photon Controller peer node at IP address [10.110.48.60]
2017-04-28 08:29:39 INFO  Info: 1 Photon Controller was specified in the configuration
2017-04-28 08:29:39 INFO  Start [Task: Photon Controller Installation]
2017-04-28 08:29:39 INFO  Info [Task: Photon Controller Installation] : Deploying and powering on the Photon Controller VM on ESXi host: 10.110.48.56
2017-04-28 08:29:39 INFO  Info: Deploying and powering on the Photon Controller VM on ESXi host: 10.110.48.56
2017-04-28 08:29:39 INFO  Info [Task: Photon Controller Installation] : Starting appliance deployment
2017-04-28 08:29:52 INFO  Progress [Task: Photon Controller Installation]: 20%
2017-04-28 08:29:56 INFO  Progress [Task: Photon Controller Installation]: 40%
2017-04-28 08:30:00 INFO  Progress [Task: Photon Controller Installation]: 60%
2017-04-28 08:30:05 INFO  Progress [Task: Photon Controller Installation]: 80%
2017-04-28 08:30:10 INFO  Progress [Task: Photon Controller Installation]: 0%
2017-04-28 08:30:10 INFO  Stop [Task: Photon Controller Installation]
2017-04-28 08:30:10 INFO  Info: Getting OIDC Tokens from Lightwave to make API Calls
2017-04-28 08:30:11 INFO  Info: Waiting for Photon Controller to be ready
2017-04-28 08:40:50 ERROR Error: The PC node at 10.110.48.60 failed to provide correct status after 300 iterations
2017-04-28 08:40:50 ERROR Error: Failed to install Controller Cluster
com.vmware.photon.platform.setup.installer.InstallException: The PC node at 10.110.48.60 failed to provide correct status after 300 iterations
        at com.vmware.photon.platform.setup.installer.ControllerClusterInstaller.checkPhotonStatus(ControllerClusterInstaller.java:262)
        at com.vmware.photon.platform.setup.installer.ControllerClusterInstaller.install(ControllerClusterInstaller.java:165)
        at com.vmware.photon.platform.setup.installer.PhotonSetupImpl.InstallPhotonControllerCluster(PhotonSetupImpl.java:87)
        at com.vmware.photon.platform.setup.PlatformInstaller.InstallPhoton(PlatformInstaller.java:143)
        at com.vmware.photon.platform.setup.PlatformInstaller.install(PlatformInstaller.java:73)
        at com.vmware.photon.platform.setup.PhotonSetup.main(PhotonSetup.java:47)
com.vmware.photon.platform.setup.installer.InstallException: Error: Failed to install Controller Cluster

The configuration used is this:
compute:
  hypervisors:
    esxi-1:
      hostname: "esxi-1"
      ipaddress: "10.110.48.56"
      dns: "10.112.64.1"
      credential:
        username: "root"
        password: "Ca$hc0w1"
lightwave:
  domain: "dvs.com"
  credential:
    username: "administrator"
    password: "Ca$hc0w1"
  controllers:
    lightwave-1:
      site: "blr"
      appliance:
        hostref: "esxi-1"
        datastore: "bigone"
        credential:
          username: "root"
          password: "Ca$hc0w1"
        network-config:
          network: "NAT=VM Network"
          type: "static"
          hostname: "lightwave-1.example.com"
          ipaddress: "10.110.48.59"
          dns: "10.112.64.1"
          ntp: ""
          netmask: "255.255.255.192"
          gateway: "10.110.48.61"
photon:
  imagestore:
    img-store-1:
      datastore: "bigone"
      enableimagestoreforvms: "true"
  cloud:
    hostref1: "esxi-1"
  controllers:
    pc-1:
      appliance:
        hostref: "esxi-1"
        datastore: "bigone"
        credential:
          username: "root"
          password: "Ca$hc0w1"
        network-config:
          network: "NAT=VM Network"
          type: "static"
          hostname: "pc-1.example.com"
          ipaddress: "10.110.48.60"
          netmask: "255.255.255.192"
          dns: "10.110.48.59"
          ntp: ""
          gateway: "10.110.48.61"
loadBalancer:
  load-balancer-1:
    appliance:
      hostref: "esxi-1"
      datastore: "bigone"
      credential:
        username: "root"
        password: "Ca$hc0w1"
      network-config:
        network: "NAT=VM Network"
        type: "static"
        hostname: "lb-1.example.com"
        ipaddress: "10.110.48.57"
        netmask: "255.255.255.192"
        dns: "10.110.48.59"
        ntp: ""
        gateway: "10.110.48.61"

**Comment by govint** [comment]
photon-installer.log has these lines at the end.

2017-04-28 08:40:21 DEBUG ControllerClusterInstaller:256 - Info: Checking if photon controller service is running at 10.110.48.60 : Count 287
2017-04-28 08:40:22 DEBUG ControllerClusterInstaller:346 - https://10.110.48.60:9000/v1/system/status
2017-04-28 08:40:23 DEBUG ControllerClusterInstaller:256 - Info: Checking if photon controller service is running at 10.110.48.60 : Count 288
2017-04-28 08:40:24 DEBUG ControllerClusterInstaller:346 - https://10.110.48.60:9000/v1/system/status
2017-04-28 08:40:25 DEBUG ControllerClusterInstaller:256 - Info: Checking if photon controller service is running at 10.110.48.60 : Count 289
2017-04-28 08:40:26 DEBUG ControllerClusterInstaller:346 - https://10.110.48.60:9000/v1/system/status
2017-04-28 08:40:27 DEBUG ControllerClusterInstaller:256 - Info: Checking if photon controller service is running at 10.110.48.60 : Count 290
2017-04-28 08:40:28 DEBUG ControllerClusterInstaller:346 - https://10.110.48.60:9000/v1/system/status
2017-04-28 08:40:29 DEBUG ControllerClusterInstaller:256 - Info: Checking if photon controller service is running at 10.110.48.60 : Count 291
2017-04-28 08:40:30 DEBUG ControllerClusterInstaller:346 - https://10.110.48.60:9000/v1/system/status
2017-04-28 08:40:31 DEBUG ControllerClusterInstaller:256 - Info: Checking if photon controller service is running at 10.110.48.60 : Count 292
2017-04-28 08:40:32 DEBUG ControllerClusterInstaller:346 - https://10.110.48.60:9000/v1/system/status
2017-04-28 08:40:33 DEBUG ControllerClusterInstaller:256 - Info: Checking if photon controller service is running at 10.110.48.60 : Count 293
2017-04-28 08:40:35 DEBUG ControllerClusterInstaller:346 - https://10.110.48.60:9000/v1/system/status
2017-04-28 08:40:36 DEBUG ControllerClusterInstaller:256 - Info: Checking if photon controller service is running at 10.110.48.60 : Count 294
2017-04-28 08:40:37 DEBUG ControllerClusterInstaller:346 - https://10.110.48.60:9000/v1/system/status
2017-04-28 08:40:38 DEBUG ControllerClusterInstaller:256 - Info: Checking if photon controller service is running at 10.110.48.60 : Count 295
2017-04-28 08:40:39 DEBUG ControllerClusterInstaller:346 - https://10.110.48.60:9000/v1/system/status
2017-04-28 08:40:40 DEBUG ControllerClusterInstaller:256 - Info: Checking if photon controller service is running at 10.110.48.60 : Count 296
2017-04-28 08:40:41 DEBUG ControllerClusterInstaller:346 - https://10.110.48.60:9000/v1/system/status
2017-04-28 08:40:42 DEBUG ControllerClusterInstaller:256 - Info: Checking if photon controller service is running at 10.110.48.60 : Count 297
2017-04-28 08:40:43 DEBUG ControllerClusterInstaller:346 - https://10.110.48.60:9000/v1/system/status
2017-04-28 08:40:44 DEBUG ControllerClusterInstaller:256 - Info: Checking if photon controller service is running at 10.110.48.60 : Count 298
2017-04-28 08:40:45 DEBUG ControllerClusterInstaller:346 - https://10.110.48.60:9000/v1/system/status
2017-04-28 08:40:46 DEBUG ControllerClusterInstaller:256 - Info: Checking if photon controller service is running at 10.110.48.60 : Count 299
2017-04-28 08:40:47 DEBUG ControllerClusterInstaller:346 - https://10.110.48.60:9000/v1/system/status
2017-04-28 08:40:48 DEBUG ControllerClusterInstaller:256 - Info: Checking if photon controller service is running at 10.110.48.60 : Count 300
2017-04-28 08:40:49 DEBUG ControllerClusterInstaller:346 - https://10.110.48.60:9000/v1/system/status
2017-04-28 08:40:50 ERROR ControllerClusterInstaller:261 - Error: The PC node at 10.110.48.60 failed to provide correct status after 300 iterations
2017-04-28 08:40:50 ERROR PhotonSetupImpl:90 - Error: Failed to install Controller Cluster
com.vmware.photon.platform.setup.installer.InstallException: The PC node at 10.110.48.60 failed to provide correct status after 300 iterations
        at com.vmware.photon.platform.setup.installer.ControllerClusterInstaller.checkPhotonStatus(ControllerClusterInstaller.java:262)
        at com.vmware.photon.platform.setup.installer.ControllerClusterInstaller.install(ControllerClusterInstaller.java:165)
        at com.vmware.photon.platform.setup.installer.PhotonSetupImpl.InstallPhotonControllerCluster(PhotonSetupImpl.java:87)
        at com.vmware.photon.platform.setup.PlatformInstaller.InstallPhoton(PlatformInstaller.java:143)
        at com.vmware.photon.platform.setup.PlatformInstaller.install(PlatformInstaller.java:73)
        at com.vmware.photon.platform.setup.PhotonSetup.main(PhotonSetup.java:47)

**Comment by pompomJuice** [comment]
You are short a line:

`administrator-group: "dvs.com\\Administrators"`

Make sure you put that in or lightwave wont function.

**Comment by govint** [comment]
Thanks, where do I insert that in the installer yaml.

**Comment by pompomJuice** [comment]
Below and at the same indentation level as the `cloud:` tag

Check the example config.

**Comment by PetrMc** [comment]
having the same problem - group was already in there.

here is my config

compute:
  hypervisors:
    esxi-1:
      hostname: "pc-1"
      ipaddress: "192.168.110.51"
      dns: "192.168.110.10"
      credential:
        username: "root"
        password: "VMware1!"
    esxi-2:
      hostname: "pc-2"
      ipaddress: "192.168.110.52"
      dns: "192.168.110.10"
      credential:
        username: "root"
        password: "VMware1!"
    esxi-3:
      hostname: "pc-3"
      ipaddress: "192.168.110.53"
      dns: "192.168.110.10"
      credential:
        username: "root"
        password: "VMware1!"
    esxi-4:
      hostname: "pc-4"
      ipaddress: "192.168.110.54"
      dns: "192.168.110.10"
      credential:
        username: "root"
        password: "VMware1!"
    esxi-5:
      hostname: "pc-5"
      ipaddress: "192.168.110.55"
      dns: "192.168.110.10"
      credential:
        username: "root"
        password: "VMware1!"
lightwave:
  domain: "corp.local"
  credential:
    username: "administrator"
    password: "Secret123$"
  controllers:
    lightwave-1:
      site: "new york"
      appliance:
        hostref: "esxi-1"
        datastore: "iscsi1"
        memoryMb: 2048
        cpus: 2
        credential:
          username: "root"
          password: "VMware1!"
        network-config:
          type: "static"
          hostname: "lightwave-1.corp.local"
          ipaddress: "192.168.110.91"
          network: "NAT=VM Network"
          dns: "192.168.110.10"
          ntp: "192.168.110.1"
          netmask: "255.255.255.0"
          gateway: "192.168.110.1"
photon:
  imagestore:
    img-store-1:
      datastore: "iscsi1"
      enableimagestoreforvms: "true"
  cloud:
    hostref-1: "esxi-5"
    hostref-2: "esxi-3"
  administrator-group: "corp.local\\Administrators"
  syslog:
    ipaddress: "192.168.110.23"
  controllers:
    pc-1:
      appliance:
        hostref: "esxi-1"
        datastore: "iscsi1"
        memoryMb: 2048
        cpus: 2
        credential:
          username: "root"
          password: "VMware1!"
        network-config:
          type: "static"
          hostname: "pc-1.corp.local"
          ipaddress: "192.168.110.94"
          network: "NAT=VM Network"
          netmask: "255.255.255.0"
          dns: "192.168.110.10"
          ntp: "192.168.110.1"
          gateway: "192.168.110.1"
loadBalancer:
  load-balancer-1:
    appliance:
      hostref: "esxi-1"
      datastore: "iscsi1"
      memoryMb: 2048
      cpus: 2
      credential:
        username: "root"
        password: "VMware1!"
      network-config:
        type: "static"
        hostname: "lb-1.corp.local"
        ipaddress: "192.168.110.21"
        network: "NAT=VM Network"
        netmask: "255.255.255.0"
        dns: "192.168.110.10"
        ntp: "192.168.110.1"
        gateway: "192.168.110.1"

**Comment by mwest44** [comment]
DNS for your hosts and controllers must be the IP address of the LW VM (192.168.110.91)
You also should make sure that your hosts do not already have three DNS servers configured.  ESXi only supports 3 and we need to add LW as DNS

**Comment by PetrMc** [comment]
Thank you Michael - it worked with no issues!

**Comment by govint** [comment]
Tried out but looks like what I'm observing is a different issue. I can repro and pass on any logs if needed.

**Comment by pompomJuice** [comment]
@govint Create a new issue with new logs.

**Comment by rushins** [comment]
Hello Michael.
i got the same error and i changed "controller" to IP instead FQDN  but it still failing overall.
com.vmware.photon.platform.setup.installer.InstallException: Error: Failed to install Controller Cluster

any idea whats going wrong.
