### ISSUE TITLE
com.vmware.photon.platform.setup.installer.InstallException: Error: Failed to install Register Host

### ISSUE THREAD

**Issue by atozprasad** [vmware/photon-controller#124]
ERROR Error: Failed to install Register Host
java.lang.RuntimeException: Task failed to provide correct state ERROR
	at com.vmware.photon.platform.setup.installer.ControllerInstaller.RegisterHost(ControllerInstaller.java:454)
	at com.vmware.photon.platform.setup.installer.PhotonSetupImpl.RegisterHost(PhotonSetupImpl.java:176)
	at com.vmware.photon.platform.setup.PlatformInstaller.InstallAgent(PlatformInstaller.java:198)
	at com.vmware.photon.platform.setup.PlatformInstaller.install(PlatformInstaller.java:77)
	at com.vmware.photon.platform.setup.PhotonSetup.main(PhotonSetup.java:47)
com.vmware.photon.platform.setup.installer.InstallException: Error: Failed to install Register Host

**Comment by atozprasad** [comment]
Failed to deploy Photon Controller with NSX-T configuration. My Yaml file for the NSX section  looks as below  

nsxconfig:
  ipaddress: "192.168.60.16"
  credential:
    username: "admin"
    password: "admin"
  privateIpRootCidr: "10.20.0.0/24"
  floatingIpRootRange: "192.168.60.200-192.168.60.250"
  t0RouterId: "b938f982-2925-426f-abea-7321469d31e9"
  edgeClusterId: "3e262055-c0df-42a3-8730-3cfe419ccf60"
  overlayTransportZoneId: "1335ab0d-b30d-4d7c-907b-aa071f4d5f73"
  tunnelIpPoolId: "f4908424-0af0-4f15-8b6c-27311ce239b3"
  hostUplinkPnic: "12002b5a-4577-45e4-8a7c-294dd6b0edc1"
  hostUplinkVlanId: "0"
  dnsServerAddresses: "LightwaveVMIPAddress"

**Comment by atozprasad** [comment]
Issue occured because of pre-existing NSX-T installation of hosts. After a clean re-install of ESXI only hosts photon setup went through fine. 
Take Out: Photon will install the NSX VIB on ESXI host for you. So you should handover ESXI only hosts to photon ( without NSXT setup). Btw.. NSX-T Manager in entirely isolated Host.
