### ISSUE TITLE
Failed to install Controller Cluster

### ISSUE THREAD

**Issue by althepcman** [vmware/photon-controller#144]
Using configuration at install.yaml
INFO: Parsing Lightwave Configuration
INFO: Parsing Credentials
INFO: Lightwave Credentials parsed successfully
INFO: Parsing Lightwave Controller Config
INFO: Parsing appliance
INFO: Parsing Credentials
INFO: Appliance Credentials parsed successfully
INFO: Parsing Network Config
INFO: Appliance network config parsed successfully
INFO: Appliance config parsed successfully
INFO: Lightwave Controller parsed successfully
INFO: Lightwave Controller config parsed successfully
INFO: Lightwave Section parsed successfully
INFO: Parsing Photon Controller Configuration
INFO: Parsing Photon Controller Image Store
INFO: Image Store parsed successfully
INFO: Managed hosts parsed successfully
INFO: Syslog parsed successfully
INFO: Parsing Photon Controller Config
INFO: Parsing appliance
INFO: Parsing Credentials
INFO: Appliance Credentials parsed successfully
INFO: Parsing Network Config
INFO: Appliance network config parsed successfully
INFO: Photon Controllers parsed successfully
INFO: Photon section parsed successfully
INFO: Parsing Compute Configuration
INFO: Parsing Compute Config
INFO: Parsing Credentials
INFO: Parsing Credentials
INFO: Compute Config parsed successfully
INFO: Parsing LoadBalancer Configuration
INFO: Parsing LoadBalancer Config
INFO: Parsing appliance
INFO: Parsing Credentials
INFO: Appliance Credentials parsed successfully
INFO: Parsing Network Config
INFO: Appliance network config parsed successfully
INFO: LoadBalancer Config parsed successfully
INFO: Parsing Credentials
Validating configuration
Validating compute configuration
Validating identity configuration
Validating photon configuration
2018-02-19 03:09:19 INFO  Installing Lightwave
2018-02-19 03:09:19 INFO  Install Lightwave Controller at lightwave-1
2018-02-19 03:09:38 INFO  Info: Lightwave does not exist at the specified IP address. Deploying new Lightwave OVA
2018-02-19 03:09:38 INFO  Start [Task: Lightwave Installation]
2018-02-19 03:09:38 INFO  Info [Task: Lightwave Installation] : Deploying and powering on the Lightwave VM on ESXi host: 10.130.128.61
2018-02-19 03:09:38 INFO  Info: Deploying and powering on the Lightwave VM on ESXi host: 10.130.128.61
2018-02-19 03:09:38 INFO  Info [Task: Lightwave Installation] : Starting appliance deployment
2018-02-19 03:09:51 INFO  Progress [Task: Lightwave Installation]: 20%
2018-02-19 03:09:55 INFO  Progress [Task: Lightwave Installation]: 40%
2018-02-19 03:10:02 INFO  Progress [Task: Lightwave Installation]: 80%
2018-02-19 03:10:09 INFO  Progress [Task: Lightwave Installation]: 0%
2018-02-19 03:10:09 INFO  Stop [Task: Lightwave Installation]
2018-02-19 03:11:10 INFO  Info: Lightwave already exists. Skipping deployment of lightwave.
2018-02-19 03:11:10 INFO  COMPLETE: Install Lightwave Controller
2018-02-19 03:11:10 INFO  Installing Photon Controller Cluster
2018-02-19 03:11:10 INFO  Info: Installing the Photon Controller Cluster
2018-02-19 03:11:10 INFO  Info: Photon Controller peer node at IP address [10.130.128.21]
2018-02-19 03:11:10 INFO  Info: 1 Photon Controller was specified in the configuration
2018-02-19 03:11:10 INFO  Start [Task: Photon Controller Installation]
2018-02-19 03:11:10 INFO  Info [Task: Photon Controller Installation] : Deploying and powering on the Photon Controller VM on ESXi host: 10.130.128.61
2018-02-19 03:11:10 INFO  Info: Deploying and powering on the Photon Controller VM on ESXi host: 10.130.128.61
2018-02-19 03:11:10 INFO  Info [Task: Photon Controller Installation] : Starting appliance deployment
2018-02-19 03:11:23 INFO  Progress [Task: Photon Controller Installation]: 20%
2018-02-19 03:11:27 INFO  Progress [Task: Photon Controller Installation]: 40%
2018-02-19 03:11:31 INFO  Progress [Task: Photon Controller Installation]: 60%
2018-02-19 03:11:34 INFO  Progress [Task: Photon Controller Installation]: 80%
2018-02-19 03:11:40 INFO  Progress [Task: Photon Controller Installation]: 0%
2018-02-19 03:11:40 INFO  Stop [Task: Photon Controller Installation]
2018-02-19 03:11:40 INFO  Info: Getting OIDC Tokens from Lightwave to make API Calls
2018-02-19 03:11:41 INFO  Info: Waiting for Photon Controller to be ready
2018-02-19 03:22:20 ERROR Error: The PC node at 10.130.128.21 failed to provide correct status after 300 iterations
2018-02-19 03:22:20 ERROR Error: Failed to install Controller Cluster
com.vmware.photon.platform.setup.installer.InstallException: The PC node at 10.130.128.21 failed to provide correct status after 300 iterations
        at com.vmware.photon.platform.setup.installer.ControllerClusterInstaller.checkPhotonStatus(ControllerClusterInstaller.java:262)
        at com.vmware.photon.platform.setup.installer.ControllerClusterInstaller.install(ControllerClusterInstaller.java:165)
        at com.vmware.photon.platform.setup.installer.PhotonSetupImpl.InstallPhotonControllerCluster(PhotonSetupImpl.java:87)
        at com.vmware.photon.platform.setup.PlatformInstaller.InstallPhoton(PlatformInstaller.java:143)
        at com.vmware.photon.platform.setup.PlatformInstaller.install(PlatformInstaller.java:73)
        at com.vmware.photon.platform.setup.PhotonSetup.main(PhotonSetup.java:47)
com.vmware.photon.platform.setup.installer.InstallException: Error: Failed to install Controller Cluster
root@photon-installer [ ~ ]# vi install.yaml
root@photon-installer [ ~ ]# photon-setup platform install -config install.yaml
Using configuration at install.yaml
INFO: Parsing Lightwave Configuration
INFO: Parsing Credentials
INFO: Lightwave Credentials parsed successfully
INFO: Parsing Lightwave Controller Config
INFO: Parsing appliance
INFO: Parsing Credentials
INFO: Appliance Credentials parsed successfully
INFO: Parsing Network Config
INFO: Appliance network config parsed successfully
INFO: Appliance config parsed successfully
INFO: Lightwave Controller parsed successfully
INFO: Lightwave Controller config parsed successfully
INFO: Lightwave Section parsed successfully
INFO: Parsing Photon Controller Configuration
INFO: Parsing Photon Controller Image Store
INFO: Image Store parsed successfully
INFO: Managed hosts parsed successfully
INFO: Syslog parsed successfully
INFO: Parsing Photon Controller Config
INFO: Parsing appliance
INFO: Parsing Credentials
INFO: Appliance Credentials parsed successfully
INFO: Parsing Network Config
INFO: Appliance network config parsed successfully
INFO: Photon Controllers parsed successfully
INFO: Photon section parsed successfully
INFO: Parsing Compute Configuration
INFO: Parsing Compute Config
INFO: Parsing Credentials
INFO: Parsing Credentials
INFO: Compute Config parsed successfully
INFO: Parsing LoadBalancer Configuration
INFO: Parsing LoadBalancer Config
INFO: Parsing appliance
INFO: Parsing Credentials
INFO: Appliance Credentials parsed successfully
INFO: Parsing Network Config
INFO: Appliance network config parsed successfully
INFO: LoadBalancer Config parsed successfully
INFO: Parsing Credentials
Validating configuration
Validating compute configuration
Validating identity configuration
Validating photon configuration
2018-02-19 03:30:08 INFO  Installing Lightwave
2018-02-19 03:30:08 INFO  Install Lightwave Controller at lightwave-1
2018-02-19 03:30:27 INFO  Info: Lightwave does not exist at the specified IP address. Deploying new Lightwave OVA
2018-02-19 03:30:27 INFO  Start [Task: Lightwave Installation]
2018-02-19 03:30:27 INFO  Info [Task: Lightwave Installation] : Deploying and powering on the Lightwave VM on ESXi host: 10.130.128.61
2018-02-19 03:30:27 INFO  Info: Deploying and powering on the Lightwave VM on ESXi host: 10.130.128.61
2018-02-19 03:30:27 INFO  Info [Task: Lightwave Installation] : Starting appliance deployment
2018-02-19 03:30:40 INFO  Progress [Task: Lightwave Installation]: 20%
2018-02-19 03:30:44 INFO  Progress [Task: Lightwave Installation]: 40%
2018-02-19 03:30:52 INFO  Progress [Task: Lightwave Installation]: 80%
2018-02-19 03:30:57 INFO  Progress [Task: Lightwave Installation]: 0%
2018-02-19 03:30:57 INFO  Stop [Task: Lightwave Installation]
2018-02-19 03:31:55 INFO  Info: Lightwave already exists. Skipping deployment of lightwave.
2018-02-19 03:31:55 INFO  COMPLETE: Install Lightwave Controller
2018-02-19 03:31:55 INFO  Installing Photon Controller Cluster
2018-02-19 03:31:55 INFO  Info: Installing the Photon Controller Cluster
2018-02-19 03:31:55 INFO  Info: Photon Controller peer node at IP address [10.130.128.21]
2018-02-19 03:31:55 INFO  Info: 1 Photon Controller was specified in the configuration
2018-02-19 03:31:55 INFO  Start [Task: Photon Controller Installation]
2018-02-19 03:31:55 INFO  Info [Task: Photon Controller Installation] : Deploying and powering on the Photon Controller VM on ESXi host: 10.130.128.61
2018-02-19 03:31:55 INFO  Info: Deploying and powering on the Photon Controller VM on ESXi host: 10.130.128.61
2018-02-19 03:31:55 INFO  Info [Task: Photon Controller Installation] : Starting appliance deployment
2018-02-19 03:32:07 INFO  Progress [Task: Photon Controller Installation]: 20%
2018-02-19 03:32:11 INFO  Progress [Task: Photon Controller Installation]: 40%
2018-02-19 03:32:15 INFO  Progress [Task: Photon Controller Installation]: 60%
2018-02-19 03:32:19 INFO  Progress [Task: Photon Controller Installation]: 80%
2018-02-19 03:32:24 INFO  Progress [Task: Photon Controller Installation]: 0%
2018-02-19 03:32:25 INFO  Stop [Task: Photon Controller Installation]
2018-02-19 03:32:25 INFO  Info: Getting OIDC Tokens from Lightwave to make API Calls
2018-02-19 03:32:26 INFO  Info: Waiting for Photon Controller to be ready
2018-02-19 03:43:05 ERROR Error: The PC node at 10.130.128.21 failed to provide correct status after 300 iterations
2018-02-19 03:43:05 ERROR Error: Failed to install Controller Cluster
com.vmware.photon.platform.setup.installer.InstallException: The PC node at 10.130.128.21 failed to provide correct status after 300 iterations
        at com.vmware.photon.platform.setup.installer.ControllerClusterInstaller.checkPhotonStatus(ControllerClusterInstaller.java:262)
        at com.vmware.photon.platform.setup.installer.ControllerClusterInstaller.install(ControllerClusterInstaller.java:165)
        at com.vmware.photon.platform.setup.installer.PhotonSetupImpl.InstallPhotonControllerCluster(PhotonSetupImpl.java:87)
        at com.vmware.photon.platform.setup.PlatformInstaller.InstallPhoton(PlatformInstaller.java:143)
        at com.vmware.photon.platform.setup.PlatformInstaller.install(PlatformInstaller.java:73)
        at com.vmware.photon.platform.setup.PhotonSetup.main(PhotonSetup.java:47)
com.vmware.photon.platform.setup.installer.InstallException: Error: Failed to install Controller Cluster
root@photon-installer [ ~ ]# vi install.yaml
root@photon-installer [ ~ ]# vi install.yaml
root@photon-installer [ ~ ]# photon-setup platform install -config install.yaml
Using configuration at install.yaml
INFO: Parsing Lightwave Configuration
INFO: Parsing Credentials
INFO: Lightwave Credentials parsed successfully
INFO: Parsing Lightwave Controller Config
INFO: Parsing appliance
INFO: Parsing Credentials
INFO: Appliance Credentials parsed successfully
INFO: Parsing Network Config
INFO: Appliance network config parsed successfully
INFO: Appliance config parsed successfully
INFO: Lightwave Controller parsed successfully
INFO: Lightwave Controller config parsed successfully
INFO: Lightwave Section parsed successfully
INFO: Parsing Photon Controller Configuration
INFO: Parsing Photon Controller Image Store
INFO: Image Store parsed successfully
INFO: Managed hosts parsed successfully
INFO: Syslog parsed successfully
INFO: Parsing Photon Controller Config
INFO: Parsing appliance
INFO: Parsing Credentials
INFO: Appliance Credentials parsed successfully
INFO: Parsing Network Config
INFO: Appliance network config parsed successfully
INFO: Photon Controllers parsed successfully
INFO: Photon section parsed successfully
INFO: Parsing Compute Configuration
INFO: Parsing Compute Config
INFO: Parsing Credentials
INFO: Parsing Credentials
INFO: Compute Config parsed successfully
INFO: Parsing LoadBalancer Configuration
INFO: Parsing LoadBalancer Config
INFO: Parsing appliance
INFO: Parsing Credentials
INFO: Appliance Credentials parsed successfully
INFO: Parsing Network Config
INFO: Appliance network config parsed successfully
INFO: LoadBalancer Config parsed successfully
INFO: Parsing Credentials
Validating configuration
Validating compute configuration
Validating identity configuration
Validating photon configuration
2018-02-19 03:59:27 INFO  Installing Lightwave
2018-02-19 03:59:27 INFO  Install Lightwave Controller at lightwave-1
2018-02-19 03:59:47 INFO  Info: Lightwave does not exist at the specified IP address. Deploying new Lightwave OVA
2018-02-19 03:59:47 INFO  Start [Task: Lightwave Installation]
2018-02-19 03:59:47 INFO  Info [Task: Lightwave Installation] : Deploying and powering on the Lightwave VM on ESXi host: 10.130.128.61
2018-02-19 03:59:47 INFO  Info: Deploying and powering on the Lightwave VM on ESXi host: 10.130.128.61
2018-02-19 03:59:47 INFO  Info [Task: Lightwave Installation] : Starting appliance deployment
2018-02-19 03:59:58 INFO  Progress [Task: Lightwave Installation]: 20%
2018-02-19 04:00:02 INFO  Progress [Task: Lightwave Installation]: 40%
2018-02-19 04:00:10 INFO  Progress [Task: Lightwave Installation]: 80%
2018-02-19 04:00:16 INFO  Progress [Task: Lightwave Installation]: 0%
2018-02-19 04:00:16 INFO  Stop [Task: Lightwave Installation]
2018-02-19 04:01:19 INFO  Info: Lightwave already exists. Skipping deployment of lightwave.
2018-02-19 04:01:19 INFO  COMPLETE: Install Lightwave Controller
2018-02-19 04:01:19 INFO  Installing Photon Controller Cluster
2018-02-19 04:01:19 INFO  Info: Installing the Photon Controller Cluster
2018-02-19 04:01:19 INFO  Info: Photon Controller peer node at IP address [10.130.128.21]
2018-02-19 04:01:19 INFO  Info: 1 Photon Controller was specified in the configuration
2018-02-19 04:01:19 INFO  Start [Task: Photon Controller Installation]
2018-02-19 04:01:19 INFO  Info [Task: Photon Controller Installation] : Deploying and powering on the Photon Controller VM on ESXi host: 10.130.128.61
2018-02-19 04:01:19 INFO  Info: Deploying and powering on the Photon Controller VM on ESXi host: 10.130.128.61
2018-02-19 04:01:19 INFO  Info [Task: Photon Controller Installation] : Starting appliance deployment
2018-02-19 04:01:32 INFO  Progress [Task: Photon Controller Installation]: 20%
2018-02-19 04:01:36 INFO  Progress [Task: Photon Controller Installation]: 40%
2018-02-19 04:01:40 INFO  Progress [Task: Photon Controller Installation]: 60%
2018-02-19 04:01:44 INFO  Progress [Task: Photon Controller Installation]: 80%
2018-02-19 04:01:50 INFO  Progress [Task: Photon Controller Installation]: 0%
2018-02-19 04:01:50 INFO  Stop [Task: Photon Controller Installation]
2018-02-19 04:01:50 INFO  Info: Getting OIDC Tokens from Lightwave to make API Calls
2018-02-19 04:01:51 INFO  Info: Waiting for Photon Controller to be ready
2018-02-19 04:12:30 ERROR Error: The PC node at 10.130.128.21 failed to provide correct status after 300 iterations
2018-02-19 04:12:30 ERROR Error: Failed to install Controller Cluster
com.vmware.photon.platform.setup.installer.InstallException: The PC node at 10.130.128.21 failed to provide correct status after 300 iterations
        at com.vmware.photon.platform.setup.installer.ControllerClusterInstaller.checkPhotonStatus(ControllerClusterInstaller.java:262)
        at com.vmware.photon.platform.setup.installer.ControllerClusterInstaller.install(ControllerClusterInstaller.java:165)
        at com.vmware.photon.platform.setup.installer.PhotonSetupImpl.InstallPhotonControllerCluster(PhotonSetupImpl.java:87)
        at com.vmware.photon.platform.setup.PlatformInstaller.InstallPhoton(PlatformInstaller.java:143)
        at com.vmware.photon.platform.setup.PlatformInstaller.install(PlatformInstaller.java:73)
        at com.vmware.photon.platform.setup.PhotonSetup.main(PhotonSetup.java:47)
com.vmware.photon.platform.setup.installer.InstallException: Error: Failed to install Controller Cluster
root@photon-installer [ ~ ]# photon-setup platform install -config install.yaml
Using configuration at install.yaml
INFO: Parsing Lightwave Configuration
INFO: Parsing Credentials
INFO: Lightwave Credentials parsed successfully
INFO: Parsing Lightwave Controller Config
INFO: Parsing appliance
INFO: Parsing Credentials
INFO: Appliance Credentials parsed successfully
INFO: Parsing Network Config
INFO: Appliance network config parsed successfully
INFO: Appliance config parsed successfully
INFO: Lightwave Controller parsed successfully
INFO: Lightwave Controller config parsed successfully
INFO: Lightwave Section parsed successfully
INFO: Parsing Photon Controller Configuration
INFO: Parsing Photon Controller Image Store
INFO: Image Store parsed successfully
INFO: Managed hosts parsed successfully
INFO: Syslog parsed successfully
INFO: Parsing Photon Controller Config
INFO: Parsing appliance
INFO: Parsing Credentials
INFO: Appliance Credentials parsed successfully
INFO: Parsing Network Config
INFO: Appliance network config parsed successfully
INFO: Photon Controllers parsed successfully
INFO: Photon section parsed successfully
INFO: Parsing Compute Configuration
INFO: Parsing Compute Config
INFO: Parsing Credentials
INFO: Parsing Credentials
INFO: Compute Config parsed successfully
INFO: Parsing LoadBalancer Configuration
INFO: Parsing LoadBalancer Config
INFO: Parsing appliance
INFO: Parsing Credentials
INFO: Appliance Credentials parsed successfully
INFO: Parsing Network Config
INFO: Appliance network config parsed successfully
INFO: LoadBalancer Config parsed successfully
INFO: Parsing Credentials
Validating configuration
Validating compute configuration
Validating identity configuration
Validating photon configuration
2018-02-19 04:14:36 INFO  Installing Lightwave
2018-02-19 04:14:36 INFO  Install Lightwave Controller at lightwave-1
2018-02-19 04:14:56 INFO  Info: Lightwave does not exist at the specified IP address. Deploying new Lightwave OVA
2018-02-19 04:14:56 INFO  Start [Task: Lightwave Installation]
2018-02-19 04:14:56 INFO  Info [Task: Lightwave Installation] : Deploying and powering on the Lightwave VM on ESXi host: 10.130.128.61
2018-02-19 04:14:56 INFO  Info: Deploying and powering on the Lightwave VM on ESXi host: 10.130.128.61
2018-02-19 04:14:56 INFO  Info [Task: Lightwave Installation] : Starting appliance deployment
2018-02-19 04:15:07 INFO  Progress [Task: Lightwave Installation]: 20%
2018-02-19 04:15:11 INFO  Progress [Task: Lightwave Installation]: 40%
2018-02-19 04:15:18 INFO  Progress [Task: Lightwave Installation]: 80%
2018-02-19 04:15:23 INFO  Progress [Task: Lightwave Installation]: 0%
2018-02-19 04:15:23 INFO  Stop [Task: Lightwave Installation]
2018-02-19 04:16:23 INFO  Info: Lightwave already exists. Skipping deployment of lightwave.
2018-02-19 04:16:23 INFO  COMPLETE: Install Lightwave Controller
2018-02-19 04:16:23 INFO  Installing Photon Controller Cluster
2018-02-19 04:16:23 INFO  Info: Installing the Photon Controller Cluster
2018-02-19 04:16:23 INFO  Info: Photon Controller peer node at IP address [10.130.128.21]
2018-02-19 04:16:23 INFO  Info: 1 Photon Controller was specified in the configuration
2018-02-19 04:16:23 INFO  Start [Task: Photon Controller Installation]
2018-02-19 04:16:23 INFO  Info [Task: Photon Controller Installation] : Deploying and powering on the Photon Controller VM on ESXi host: 10.130.128.61
2018-02-19 04:16:23 INFO  Info: Deploying and powering on the Photon Controller VM on ESXi host: 10.130.128.61
2018-02-19 04:16:23 INFO  Info [Task: Photon Controller Installation] : Starting appliance deployment
2018-02-19 04:16:35 INFO  Progress [Task: Photon Controller Installation]: 20%
2018-02-19 04:16:39 INFO  Progress [Task: Photon Controller Installation]: 40%
2018-02-19 04:16:43 INFO  Progress [Task: Photon Controller Installation]: 60%
2018-02-19 04:16:47 INFO  Progress [Task: Photon Controller Installation]: 80%
2018-02-19 04:16:51 INFO  Progress [Task: Photon Controller Installation]: 0%
2018-02-19 04:16:52 INFO  Stop [Task: Photon Controller Installation]
2018-02-19 04:16:52 INFO  Info: Getting OIDC Tokens from Lightwave to make API Calls
2018-02-19 04:16:53 INFO  Info: Waiting for Photon Controller to be ready
2018-02-19 04:27:32 ERROR Error: The PC node at 10.130.128.21 failed to provide correct status after 300 iterations
2018-02-19 04:27:32 ERROR Error: Failed to install Controller Cluster
com.vmware.photon.platform.setup.installer.InstallException: The PC node at 10.130.128.21 failed to provide correct status after 300 iterations
        at com.vmware.photon.platform.setup.installer.ControllerClusterInstaller.checkPhotonStatus(ControllerClusterInstaller.java:262)
        at com.vmware.photon.platform.setup.installer.ControllerClusterInstaller.install(ControllerClusterInstaller.java:165)
        at com.vmware.photon.platform.setup.installer.PhotonSetupImpl.InstallPhotonControllerCluster(PhotonSetupImpl.java:87)
        at com.vmware.photon.platform.setup.PlatformInstaller.InstallPhoton(PlatformInstaller.java:143)
        at com.vmware.photon.platform.setup.PlatformInstaller.install(PlatformInstaller.java:73)
        at com.vmware.photon.platform.setup.PhotonSetup.main(PhotonSetup.java:47)
com.vmware.photon.platform.setup.installer.InstallException: Error: Failed to install Controller Cluster

--------------------------------------------------------------

YAML file
compute:
  hypervisors:
    esxi-1:
      hostname: "esx-01"
      ipaddress: "10.130.128.61"
      dns: "10.130.128.11"
      credential:
        username: "root"
        password: "VMware!"
    esxi-2:
      hostname: "esx-02"
      ipaddress: "10.130.128.62"
      dns: "10.130.128.11"
      credential:
        username: "root"
        password: "VMware!"
lightwave::w
  domain: "jcu.ed.au"
  credential:
    username: "administrator"
    password: "VMware!"
  controllers:
    lightwave-1:
      site: "JCU"
      appliance:
        hostref: "esxi-1"
        datastore: "TSV-NMB2-ITVDI-VOL01"
        memoryMb: 2048
        cpus: 2
        credential:
        username: "root"
        password: "VMware!"
        network-config:
          type: "static"
          hostname: "lightwave-soit1.jcu.edu.au"
          ipaddress: "10.130.128.11"
          network: "NAT=VM Network"
          dns: "10.130.128.11"
          ntp: "137.219.255.253"
          netmask: "255.255.254.0"
          gateway: "10.130.128.1"
photon:
  imagestore:
    img-store-1:
      datastore: "TSV-NMB2-ITVDI-VOL01"
      enableimagestoreforvms: "true"
  cloud:
    hostref-1: "esxi-1"
    hostref-2: "esxi-2"
  administrator-group: "jcu.edu.au\\Administrators"
  syslog:
    ipaddress: "10.128.20.44"
  controllers:
    pc-1:
      appliance:
        hostref: "esxi-1"
        datastore: "TSV-NMB2-ITVDI-VOL01"
        memoryMb: 2048
        cpus: 2
        credential:
          username: "root"
          password: "VMware!"
        network-config:
          type: "static"
          hostname: "pc-soit1.jcu.edu.au"
          ipaddress: "10.130.128.21"
          network: "NAT=VM Network"
          netmask: "255.255.254.0"
          dns: "10.130.128.11"
          ntp: "137.219.255.253"
          gateway: "10.130.128.1"
loadBalancer:
  load-balancer-1:
    appliance:
      hostref: "esxi-1"
      datastore: "TSV-NMB2-ITVDI-VOL01"
      memoryMb: 2048
      cpus: 2
      credential:
        username: "root"
        password: "VMware!"
      network-config:
        type: "static"
        hostname: "lb-soit1.jcu.edu.au"
        ipaddress: "10.130.128.25"
        network: "NAT=VM Network"
        netmask: "255.255.254.0"
        dns: "10.130.128.11"
        ntp: "137.219.255.253"
        gateway: "10.130.128.1"
nsxconfig:
  ipaddress: "10.130.128.40"
  credential:
    username: "root"
    password: "VMware!"
  privateIpRootCidr: "10.130.128.1/23"
  floatingIpRootRange: "10.130.128.100-10.130.128.250"
  t0RouterId: "8a1bec14-8fda-44ff-8877-c9f70700b8f9"
  edgeClusterId: "f376c3c7-6db8-430d-839e-2fbd4973a2a"
  overlayTransportZoneId: "08baba12-e27c-419b-8cfb-69f78ec7daab"
  tunnelIpPoolId: "9a4cd33d-a294-47e3-aa34-8aad026a056d"
  hostUplinkPnic: "vmnic4"
  hostUplinkVlanId: "0"
  dnsServerAddresses: "10.130.128.11"

**Comment by AlainRoy** [comment]
Photon Controller is no longer actively maintained by VMware. 
https://github.com/vmware/photon-controller/blob/master/README.md
