### ISSUE TITLE
UPLOAD_IAMGE error when mgmt and cloud host are using same vsan datastore name (actual it's totally sepetated vsan configure))

### ISSUE THREAD

**Issue by crook** [vmware/photon-controller#43]
Hi Team,

I'm running photon system deploy <deploy.yaml> using develop branch. and got the following error. please help to triage this issue.

The Esx testbeds consist of 3 mgmt host and 8 cloud host. And the 3 mgmt hosts are configured as one VC cluster and vsan enabled (the datastore name is 'vsanDatastore'). The other 8 cloud hosts are also vsan enabled with 'vsanDatastore' name (The configure process is totally using RVC, which simulate the customer env and process, maybe they don't want pay to using Vcenter).

~~~
ERROR [2016-08-12 07:45:01,681] com.vmware.photon.controller.apife.commands.tasks.TaskCommand: Task 095f3b8a-4cc1-4b13-a120-d7a2318335dd failed
! com.vmware.photon.controller.apife.exceptions.external.TaskNotCompletedException: Step "StepEntity{id=null, kind=step, state=ERROR, operation=UPLOAD_IMAGE, startedTime=Fri Aug 12 07:44:51 GMT 2016, queuedTime=Fri Aug 12 07:44:51 GMT 2016, endTime=Fri Aug 12 07:45:01 GMT 2016, sequence=0, error=StepErrorEntity{id=null, kind=step-error, code=InternalError, message=Expected exactly 1 image datastore named 'vsanDatastore', found [2]}}" did not complete.


and this is the deploy yaml file:
deployment:
  resume_system: true
  image_datastores: vsanDatastore
  ntp_endpoint: ntp1.eng.vmware.com
  auth_enabled: false
  use_image_datastore_for_vms: true
  loadbalancer_enabled: true

hosts:
  - address_ranges: 10.155.64.14-10.155.64.16
    username: root
    password: ca$hc0w
    usage_tags:
    - MGMT
    metadata:
       MANAGEMENT_DATASTORE: vsanDatastore
       MANAGEMENT_NETWORK_DNS_SERVER: 10.142.7.1
       MANAGEMENT_NETWORK_GATEWAY: 10.155.127.253
       MANAGEMENT_VM_IPS: 10.155.64.200-10.155.64.202
       MANAGEMENT_NETWORK_NETMASK: 255.255.192.0
       MANAGEMENT_PORTGROUP: "VM Network"
  - address_ranges: 10.155.64.20-10.155.64.24,10.155.64.33-10.155.64.35
    username: root
    password: ca$hc0w
    usage_tags:
    - CLOUD

~~~

However, I found one work around at last. I rename the vsan datastore name to 'vsanDs' and using the following yaml file with ALLOWED_DATASTORES. and the deploy got pass this time.
~~~deployment:
  resume_system: true
  image_datastores: vsanDatastore,vsanDs
  ntp_endpoint: ntp1.eng.vmware.com
  auth_enabled: false
  use_image_datastore_for_vms: true
  loadbalancer_enabled: true

hosts:
  - address_ranges: 10.155.64.14-10.155.64.16
    username: root
    password: ca$hc0w
    usage_tags:
    - MGMT
    metadata:
       ALLOWED_DATASTORES: vsanDatastore
       MANAGEMENT_DATASTORE: vsanDatastore
       MANAGEMENT_NETWORK_DNS_SERVER: 10.142.7.1
       MANAGEMENT_NETWORK_GATEWAY: 10.155.127.253
       MANAGEMENT_VM_IPS: 10.155.64.200-10.155.64.202
       MANAGEMENT_NETWORK_NETMASK: 255.255.192.0
       MANAGEMENT_PORTGROUP: "VM Network"
  - address_ranges: 10.155.64.20-10.155.64.24,10.155.64.33-10.155.64.35
    username: root
    password: ca$hc0w
    usage_tags:
    - CLOUD
    metadata:
       ALLOWED_DATASTORES: vsanDs
~~~

So I wonder whether it's a bug if two separated vsan datastores are both using same name, that's will cause the above error. or is it wrong of my deployment? please advise.

Thanks,
Ray

**Comment by crook** [comment]
More trace log:
~~~
ERROR [2016-08-12 07:45:01,681] com.vmware.photon.controller.apife.commands.tasks.TaskCommand: Task 095f3b8a-4cc1-4b13-a120-d7a2318335dd failed
! com.vmware.photon.controller.apife.exceptions.external.TaskNotCompletedException: Step "StepEntity{id=null, kind=step, state=ERROR, operation=UPLOAD_IMAGE, startedTime=Fri Aug 12 07:44:51 GMT 2016, queuedTime=Fri Aug 12 07:44:51 GMT 2016, endTime=Fri Aug 12 07:45:01 GMT 2016, sequence=0, error=StepErrorEntity{id=null, kind=step-error, code=InternalError, message=Expected exactly 1 image datastore named 'vsanDatastore', found [2]}}" did not complete.
! at com.vmware.photon.controller.apife.commands.tasks.TaskCommand.execute(TaskCommand.java:117)
! at com.vmware.photon.controller.apife.commands.BaseCommand.run(BaseCommand.java:58)
! at com.vmware.photon.controller.apife.clients.ImageFeClient.runImageUploadSyncSteps(ImageFeClient.java:108)
! at com.vmware.photon.controller.apife.clients.ImageFeClient.create(ImageFeClient.java:68)
! at com.vmware.photon.controller.apife.resources.image.ImagesResource.parseImageDataFromRequest(ImagesResource.java:150)
! at com.vmware.photon.controller.apife.resources.image.ImagesResource.upload(ImagesResource.java:90)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
~~~

**Comment by molteanu** [comment]
Hi Ray,

if the 2 vsan clusters are actually distinct clusters you will need to use different names for them. if you do that the error above should disappear. 

Thanks.

**Comment by crook** [comment]
@macfaden, your reply makes sense. One more question. is it always the suggestion configuration that we use one single VSAN cluster for both mgmt and cloud host? is that the best practice?

**Comment by molteanu** [comment]
The image management system will operate more efficiently with fewer datastores (VASN clusters) as it will need to replicate images to fewer locations. So from that perspective having one cluster is better. 

You need to balance that with the fault tolerance and availability requirements you have for you storage.
