### ISSUE TITLE
Unsupported python version after ESXi upgrade

### ISSUE THREAD

**Issue by gregorkistler** [vmware/photon-controller#44]
Hi there,

looks like the latest patches bundled with ESXi600-201608001.zip break deployments of the PC agent. Noticed it yesterday and today on two different ESXi hosts - one of them staged a couple of minutes ago.

ESXi builds 3620759 and 3825889 use python v2.7.9. Build 4192238 which was released eight days ago and upgrades python to v2.7.11.

Part of the deployer log:

```
ERROR [2016-08-13 14:36:40,032] com.vmware.photon.controller.deployer.dcp.task.ProvisionHostTaskService: [/photon/provision-host-tasks/2f7bf93e-cc58-4211-be9b-54f4a351ebb6] esx-install-agent2 returned 1
ERROR [2016-08-13 14:36:40,040] com.vmware.photon.controller.deployer.dcp.task.ProvisionHostTaskService: [/photon/provision-host-tasks/2f7bf93e-cc58-4211-be9b-54f4a351ebb6] Script output:  [LiveInstallationError]
 Error in running ['/etc/init.d/photon-controller-agent', 'start', 'upgrade']:
 Return code: 1
 Output: Unsupported python version 2.71
 
 It is not safe to continue. Please reboot the host immediately to discard the unfinished update.
 Please refer to the log file for more details.
retrying installing vib
 [LiveInstallationError]
 Error in running ['/etc/init.d/photon-controller-agent', 'start', 'upgrade']:
 Return code: 1
 Output: Unsupported python version 2.71
 
 It is not safe to continue. Please reboot the host immediately to discard the unfinished update.
 Please refer to the log file for more details.

ERROR [2016-08-13 14:36:40,040] com.vmware.photon.controller.deployer.dcp.task.ProvisionHostTaskService: [/photon/provision-host-tasks/2f7bf93e-cc58-4211-be9b-54f4a351ebb6] java.lang.IllegalStateException: Installing VIB file photon-controller-agent-0.9.1.226-6.0.0.vib to host 10.0.1.82 failed with exit code 1
	at com.vmware.photon.controller.deployer.dcp.task.ProvisionHostTaskService.logVibInstallationFailureAndFail(ProvisionHostTaskService.java:1235)
	at com.vmware.photon.controller.deployer.dcp.task.ProvisionHostTaskService.access$700(ProvisionHostTaskService.java:96)
	at com.vmware.photon.controller.deployer.dcp.task.ProvisionHostTaskService$6.onSuccess(ProvisionHostTaskService.java:1212)
	at com.vmware.photon.controller.deployer.dcp.task.ProvisionHostTaskService$6.onSuccess(ProvisionHostTaskService.java:1207)
	at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
	at com.google.common.util.concurrent.ListenableFutureTask.done(ListenableFutureTask.java:91)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384)
	at java.util.concurrent.FutureTask.set(FutureTask.java:233)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I´m using the latest and greatest version v0.9.1.1 of photon controller.

Can anybody also confirm this issue?

Thanks

**Comment by longzhou** [comment]
Thanks for reporting the issue. I have checked in a fix, and should be included in the next release.

**Comment by gregorkistler** [comment]
Alright thank you. Release v1.0.0 solves this issue already since it seems to deploy a lower agent vib version: 0.9.1.226-6.0.0 <> 0.9.1.102-5.5.0
