### ISSUE TITLE
photon deployment show Error if kube cluster is error state

### ISSUE THREAD

**Issue by alancivita** [vmware/photon-controller#68]
Hi there,
i've tried to deploy a kubernetes cluster but it failed because i've missed some options.

so i've tried to do a ./photon deployment show 72eed89a541f4504e3690
but got this error:
./photon deployment show 72eed89a541f4504e3690
2016/11/24 11:14:22 Error: photon: Task 'bb6a8d6e5420a1b895321' is in error state: {@step=={"sequence"=>"0","state"=>"ERROR","errors"=>[photon: { HTTP status: '0', code: 'InternalError', message: 'Please contact the system administrator about request #96af1e6e-7829-46b6-8827-bf42e468b16c', data: 'map[]' }],"warnings"=>[],"operation"=>"GET_NETWORKS","startedTime"=>"1479986062648","queuedTime"=>"1479986062643","endTime"=>"1479986062672","options"=>map[cff0c27a-2437-4cd7-8d83-627521c945d2:vm]}}
API Errors: [photon: { HTTP status: '0', code: 'InternalError', message: 'Please contact the system administrator about request #96af1e6e-7829-46b6-8827-bf42e468b16c', data: 'map[]' }]

it seems that when the photon cli queries the controller and the cluster is in ERROR state, it fails to show the results.

the UI reports the cluster to be in FATAL_ERROR, see attached screenshot.

other commands such as photon vm list, image list, system status, deployment list-vms, network list and so on, work fine.
it is only the photon deployment show <ID> that doesn't work.
Deleting the cluster via UI doesn't help.

Attached the photon-controler.log 

[photon-controller.log.zip](https://github.com/vmware/photon-controller/files/611180/photon-controller.log.zip)

![snap 2016-11-24 at 11 16 28](https://cloud.githubusercontent.com/assets/23634711/20596715/b0cbd540-b237-11e6-8464-1e32afd6dc70.png)

**Comment by mwest44** [comment]
We have removed the need to include the UUID in the deployment show command.  photon deployment show will give you what you need.

There is a UI issue with cluster deployment.  We do not allow you to select the network.  The workaround is to use the CLI cluster create command to deploy the cluster.  Alternatively, you can use the photon network create command to specify the list of portgroups to use, and then use photon network set-default command to set the default network.  Once you do that, you can use the UI to create the cluster.

**Comment by alancivita** [comment]
Thanks for the reply
but the photon deployment show still fails:
./photon  deployment show
2016/11/24 13:34:18 Error: photon: Task 'bb6a8d6e5420c0ffca690' is in error state: {@step=={"sequence"=>"0","state"=>"ERROR","errors"=>[photon: { HTTP status: '0', code: 'InternalError', message: 'Please contact the system administrator about request #e208faea-f9d4-4609-9c57-6340dcd773ea', data: 'map[]' }],"warnings"=>[],"operation"=>"GET_NETWORKS","startedTime"=>"1479994458815","queuedTime"=>"1479994458809","endTime"=>"1479994458836","options"=>map[cff0c27a-2437-4cd7-8d83-627521c945d2:vm]}}
API Errors: [photon: { HTTP status: '0', code: 'InternalError', message: 'Please contact the system administrator about request #e208faea-f9d4-4609-9c57-6340dcd773ea', data: 'map[]' }]

is there anything else that i could check?

**Comment by mwest44** [comment]
what do you get when you try photon system status?

I can't see the install from the log you posted since they get archived and this is just the latest, but I am seeing  cert errors.  Is this something specific to your environment?    


Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
! at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
! at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
! at sun.security.validator.Validator.validate(Validator.java:260)
! at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
! at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281)
! at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
! at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)

**Comment by alancivita** [comment]
./photon system status
Overall status: READY

Component          Status
PHOTON_CONTROLLER  READY

i've also noticed that photon image create doesn't work anymore: it is failing with this error:
./photon image create Downloads/photon-controller/photon-custom-hw11-1.0-13c08b6.ova -n phont1 -i ON_DEMAND
2016/11/24 13:51:32 Error: photon: Task 'bb6a8d6e5420c4cf8e108' is in error state: {@step=={"sequence"=>"0","state"=>"ERROR","errors"=>[photon: { HTTP status: '0', code: 'InternalError', message: 'Please contact the system administrator about request #c33a44a6-d774-45dd-924c-536765fcee9a', data: 'map[]' }],"warnings"=>[],"operation"=>"UPLOAD_IMAGE","startedTime"=>"1479995481978","queuedTime"=>"1479995481972","endTime"=>"1479995482134","options"=>map[40cecdd4-ce9e-4c2c-8f34-d01cbce4c44e:image]}}

the attached logs are taken from the photon-controller, not from the deployer


[photon-controller.log.zip](https://github.com/vmware/photon-controller/files/611468/photon-controller.log.zip)
[photon-controller-2016-11-23.log.gz](https://github.com/vmware/photon-controller/files/611469/photon-controller-2016-11-23.log.gz)

**Comment by mwest44** [comment]
I also see this in your log:  Failed to ping 10.90.233.195

Is this the host running the Lightwave Server?

**Comment by alancivita** [comment]
No, this is the esx hosting the photon-controller, and it is reachable, just connected to it

**Comment by mwest44** [comment]
what is the the result of photon host list?  The log shows that host 72eed89a541f450525d12 has been marked as missing because the controller VM could not ping it.

**Comment by alancivita** [comment]
./photon host list
ID                     State  IP             Tags
72eed89a541f450525928  READY  10.90.233.196  CLOUD
72eed89a541f45052592b  READY  10.90.233.198  CLOUD
72eed89a541f45052592d  READY  10.90.44.101   MGMT
72eed89a541f450525d12  READY  10.90.233.195  MGMT
72eed89a541f4505260f8  READY  10.90.233.197  CLOUD

i can easily start from scratch and try to reproduce the situation if you prefer

**Comment by mwest44** [comment]
That would be great.   Unfortunately today is a holiday in the US, so engineers are not working if we have to run down an issue - and I only have a few more minutes.  Everyone is back on Monday.

**Comment by mwest44** [comment]
BTW, I've tried a bunch of different scenarios to recreate the errors you are seeing and have not been able to do it so far.

**Comment by alancivita** [comment]
no worries :)
thanks for you help!

**Comment by mwest44** [comment]
One other thing.  Because the addition of mandatory auth through Lightwave is new to this release, and there are many blogs/etc. out there based on old releases, let's make sure you are setting the endpoint correctly.     Once the deployment completes, if its not there already, point the CLI target to http://InstallerVMIP:9000 and execute photon deployment show to get the Load Balancer endpoint.  
Then execute  photon target set https://LoadBalancerIP:443    You must accept the certificates.  Verify it with photon deployment show.   You will be prompted to login with either the Lightwave admin credentials you used in the deployment yml or with one of the security groups you set up directly in Lightwave.

**Comment by alancivita** [comment]
Sure,
just destroyed the environment and cleaned up esxi host. will redeploy shortly
this time, instead of using a nested esxi host for Lighwave i'm going to use a "real" esx host.
just one last question: is it mandatory to have 2 different datastores?

**Comment by mwest44** [comment]
The only requirement for datastores is that each host must have at least one datastore that is tagged as an image datastore.  So you could use one datastore shared across all hosts, all local datastores attached to individual hosts, or some combination of that.  Remember to enable placing cloud VMs onto image datastores if you use a single datastore, otherwise you will not be able to place any VMs.
