### ISSUE TITLE
NPE when doing photon system deploy

### ISSUE THREAD

**Issue by medvedzver** [vmware/photon-controller#71]
Hi!

I've installed PC on PhotonOS as described [here](https://github.com/vmware/photon-controller/wiki/RPM-Installation-on-Photon-OS).
Here is my manifest:
```
hosts:
- metadata:
    MANAGEMENT_DATASTORE: datastore1
    MANAGEMENT_PORTGROUP: VM Network
    MANAGEMENT_NETWORK_NETMASK: 255.255.0.0
    MANAGEMENT_NETWORK_DNS_SERVER: 192.168.33.1
    MANAGEMENT_NETWORK_GATEWAY: 192.168.33.1
    MANAGEMENT_VM_IPS: 192.168.33.120
  address_ranges: 192.168.33.100
  username: root
  password: somepwd
  usage_tags:
    - CLOUD
    - MGMT
deployment:
  resume_system: true
  image_datastores:
    - datastore1
  use_image_datastore_for_vms: true
  loadbalancer_enabled: false
  auth_enabled: false
```

When I target my PC and run
`photon system deploy manifest.yml` it fails with 
```
Created deployment cac320375430c64e9f0f8
Host with ip '192.168.218.100' created: ID = cac320375430c64f4be98
2016/12/06 23:23:29 Error: photon: Task 'cac320375430c65b280b8' is in error state: {@step=={"sequence"=>"0","state"=>"ERROR","errors"=>[photon: { HTTP status: '0', code: 'InternalError', message: 'Please contact the system administrator about request #bc1e9c3f-345b-4f39-b0d3-9617f1c45eed', data: 'map[]' }],"warnings"=>[],"operation"=>"SCHEDULE_DEPLOYMENT","startedTime"=>"1481095408476","queuedTime"=>"1481095408427","endTime"=>"1481095408596","options"=>map[cac320375430c64e9f0f8:deployment]}}
API Errors: [photon: { HTTP status: '0', code: 'InternalError', message: 'Please contact the system administrator about request #bc1e9c3f-345b-4f39-b0d3-9617f1c45eed', data: 'map[]' }]
```

In logs of PC `/var/log/esxcloud/photon-controller.log` I see
```
ERROR [2016-12-07 07:23:28,591] com.vmware.photon.controller.common.xenon.host.PhotonControllerXenonHost: Uncaught exception in service http://127.0.0.1:19000/photon/workflow/deployment/cac320375430c65b51
8c8: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
        at com.vmware.photon.controller.deployer.DeployerConfig.getImageFile(DeployerConfig.java:72)
        at com.vmware.photon.controller.deployer.DeployerConfig.getManagementImageFile(DeployerConfig.java:60)
        at com.vmware.photon.controller.deployer.xenon.workflow.DeploymentWorkflowService.handleStart(DeploymentWorkflowService.java:199)
        at com.vmware.xenon.common.ServiceHost.processServiceStart(ServiceHost.java:2503)
        at com.vmware.xenon.common.ServiceHost.lambda$processServiceStart$18(ServiceHost.java:2425)
        at com.vmware.xenon.common.Operation.lambda$nestCompletion$2(Operation.java:1248)
        at com.vmware.xenon.common.Operation.completeOrFail(Operation.java:1201)
        at com.vmware.xenon.common.Operation.complete(Operation.java:1105)
        at com.vmware.xenon.common.StatefulService.handleCreate(StatefulService.java:98)
        at com.vmware.xenon.common.ServiceHost.processServiceStart(ServiceHost.java:2446)
        at com.vmware.xenon.common.ServiceHost.processServiceStart(ServiceHost.java:2406)
        at com.vmware.xenon.common.ServiceHost.handleLoadInitialStateCompletion(ServiceHost.java:2861)
        at com.vmware.xenon.common.ServiceHost.lambda$loadInitialServiceState$23(ServiceHost.java:2796)
        at com.vmware.xenon.common.Operation.completeOrFail(Operation.java:1201)
        at com.vmware.xenon.common.Operation.complete(Operation.java:1105)
        at com.vmware.xenon.services.common.LuceneDocumentIndexService.queryIndexSingle(LuceneDocumentIndexService.java:941)
        at com.vmware.xenon.services.common.LuceneDocumentIndexService.handleGetImpl(LuceneDocumentIndexService.java:800)
        at com.vmware.xenon.services.common.LuceneDocumentIndexService.handleQueryRequest(LuceneDocumentIndexService.java:589)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

WARN  [2016-12-07 07:23:28,593] com.vmware.photon.controller.common.xenon.host.PhotonControllerXenonHost: Service /photon/workflow/deployment/cac320375430c65b518c8 failed start: java.lang.NullPointerExcep
tion
WARN  [2016-12-07 07:23:28,593] com.vmware.photon.controller.common.xenon.XenonRestClient: send: WARN Action={POST}, StatusCode={500}, OperationId={6384}, Uri={http://127.0.0.1:19000/photon/workflow/deplo
yment/cac320375430c65b518c8}, Referer={127.0.0.1}, jsonBody={NOT LOGGED}
ERROR [2016-12-07 07:23:28,596] com.vmware.photon.controller.api.frontend.commands.BaseCommand: Command execution failed with exception
! com.vmware.photon.controller.common.xenon.exceptions.XenonRuntimeException: null
! at com.vmware.photon.controller.common.xenon.XenonRestClient.handleUnknownError(XenonRestClient.java:654)
! at com.vmware.photon.controller.common.xenon.XenonRestClient.handleOperationResult(XenonRestClient.java:518)
! at com.vmware.photon.controller.common.xenon.XenonRestClient.send(XenonRestClient.java:567)
! at com.vmware.photon.controller.common.xenon.XenonRestClient.post(XenonRestClient.java:156)
! at com.vmware.photon.controller.common.xenon.XenonRestClient.post(XenonRestClient.java:129)
! at com.vmware.photon.controller.api.frontend.backends.clients.PhotonControllerXenonRestClient.post(PhotonControllerXenonRestClient.java:68)
! at com.vmware.photon.controller.api.frontend.backends.clients.PhotonControllerXenonRestClient.post(PhotonControllerXenonRestClient.java:62)
! at com.vmware.photon.controller.api.frontend.backends.clients.DeployerClient.deploy(DeployerClient.java:238)
! at com.vmware.photon.controller.api.frontend.commands.steps.DeploymentCreateStepCmd.execute(DeploymentCreateStepCmd.java:65)
! at com.vmware.photon.controller.api.frontend.commands.BaseCommand.run(BaseCommand.java:58)
! at com.vmware.photon.controller.api.frontend.commands.tasks.TaskCommand.execute(TaskCommand.java:115)
! at com.vmware.photon.controller.api.frontend.commands.BaseCommand.run(BaseCommand.java:58)
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
! at java.lang.Thread.run(Thread.java:745)
```

I think it's because DeployerConfig tries to find images in /var/photon/images and I don't have this folder.
Do I need to upload an image first?  Or do I need to change config in a some way?

Thanks!

**Comment by mwest44** [comment]
Which version are you deploying?

**Comment by medvedzver** [comment]
@mwest44 
`photon -v` returns `63a4889`
Not sure how can I get PC version, but in my `/etc/yum.repos.d/photon-controller.repo` I have 
```
[photon-controller]
name=VMware Photon Controller Core Services
baseurl=https://dl.bintray.com/vmware/photon-controller/photonos1.0/v1.0.0
gpgkey=file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY
gpgcheck=0
enabled=1
skip_if_unavailable=True
```
