### ISSUE TITLE
initial setup of photon controller and lightwave fails

### ISSUE THREAD

**Issue by medvedzver** [vmware/photon-controller#84]
Hi!

I'm trying to deploy PC with Lightwave now, and it fails after spinning up a lightwave VM. 
PCInstaller version is 1.1.0

In PC logs I see :
```
INFO  [2017-01-17 00:49:21,717] com.vmware.photon.controller.deployer.xenon.workflow.BatchCreateManag
ementWorkflowService: [/photon/workflow/batch-create-mgmt-vm/aef065875463fa4b1d8a1] Moving to stage S
TARTED:WAIT_FOR_LIGHTWAVE_SERVICE
ERROR [2017-01-17 00:54:49,089] com.vmware.photon.controller.deployer.xenon.task.CreateContainerTaskS
ervice: [/deployer/tasks/create-container/aef065875463fabbd11a2] java.lang.IllegalStateException: Con
tainer null of type Lightwave on VM 192.168.218.34 failed to become ready after 300 iterations
        at com.vmware.photon.controller.deployer.xenon.task.CreateContainerTaskService.processWaitFor
ServiceSubStage(CreateContainerTaskService.java:379)
        at com.vmware.photon.controller.deployer.xenon.task.CreateContainerTaskService.lambda$process
WaitForServiceSubStage$276(CreateContainerTaskService.java:343)
        at com.vmware.xenon.common.Operation.completeOrFail(Operation.java:1201)
        at com.vmware.xenon.common.Operation.complete(Operation.java:1105)
        at com.vmware.xenon.common.ServiceHost.lambda$null$27(ServiceHost.java:3422)
        at com.vmware.xenon.common.Operation.completeOrFail(Operation.java:1201)
        at com.vmware.xenon.common.Operation.complete(Operation.java:1105)
        at com.vmware.xenon.common.StatefulService.processCompletionStagePublishAndComplete(StatefulS
ervice.java:1098)
        at com.vmware.xenon.common.StatefulService.handleRequestCompletion(StatefulService.java:784)
        at com.vmware.xenon.common.Operation.lambda$nestCompletion$1(Operation.java:1233)
        at com.vmware.xenon.common.Operation.completeOrFail(Operation.java:1201)
        at com.vmware.xenon.common.Operation.complete(Operation.java:1105)
        at com.vmware.xenon.common.StatefulService.handleGetSimple(StatefulService.java:673)
        at com.vmware.xenon.common.StatefulService.handleGet(StatefulService.java:648)
        at com.vmware.xenon.common.StatefulService.handleRequest(StatefulService.java:405)
        at com.vmware.xenon.common.StatefulService.lambda$loadAndLinkState$7(StatefulService.java:117
5)
        at com.vmware.xenon.common.Operation.lambda$nestCompletion$1(Operation.java:1233)
        at com.vmware.xenon.common.Operation.completeOrFail(Operation.java:1201)
        at com.vmware.xenon.common.Operation.complete(Operation.java:1105)
        at com.vmware.xenon.common.ServiceHost.loadServiceState(ServiceHost.java:2698)
        at com.vmware.xenon.common.StatefulService.loadAndLinkState(StatefulService.java:1177)
        at com.vmware.xenon.common.StatefulService.handleRequestLoadingAndLinkingState(StatefulService.java:465)
        at com.vmware.xenon.common.StatefulService.handleRequest(StatefulService.java:349)
        at com.vmware.xenon.common.StatefulService.handleRequest(StatefulService.java:313)
        at com.vmware.xenon.common.ServiceHost.lambda$queueOrScheduleRequest$31(ServiceHost.java:3710)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

INFO  [2017-01-17 00:54:49,090] com.vmware.photon.controller.deployer.xenon.workflow.BatchCreateManag
ementWorkflowService: [/photon/workflow/batch-create-mgmt-vm/aef065875463fa4b1d8a1] Handling patch fo
r service /photon/workflow/batch-create-mgmt-vm/aef065875463fa4b1d8a1
INFO  [2017-01-17 00:54:49,092] com.vmware.photon.controller.deployer.xenon.workflow.BatchCreateManagementWorkflowService: [/photon/workflow/batch-create-mgmt-vm/aef065875463fa4b1d8a1] Moving to stage FAILED:null
INFO  [2017-01-17 00:54:49,101] com.vmware.photon.controller.deployer.xenon.workflow.DeploymentWorkflowService:  [Req: 109a818b-aee0-45e6-a2e1-f431e20b5e90] [/photon/workflow/deployment/aef065875463f9e16fd40] Handling patch for service /photon/workflow/deployment/aef065875463f9e16fd40
INFO  [2017-01-17 00:54:49,101] com.vmware.photon.controller.deployer.xenon.workflow.DeploymentWorkflowService:  [Req: 109a818b-aee0-45e6-a2e1-f431e20b5e90] [/photon/workflow/deployment/aef065875463f9e16fd40] Moving from STARTED:CREATE_MANAGEMENT_PLANE to stage FAILED:null
INFO  [2017-01-17 00:54:52,824] com.vmware.photon.controller.api.frontend.commands.steps.DeploymentCreateStepCmd: Deployment create failed, mark entity aef065875463f9cc96ab8 state as ERROR
INFO  [2017-01-17 00:54:52,825] com.vmware.photon.controller.cloudstore.xenon.entity.DeploymentService:  [Req: 109a818b-aee0-45e6-a2e1-f431e20b5e90] [/photon/cloudstore/deployments/aef065875463f9cc96ab8] Handling patch for service /photon/cloudstore/deployments/aef065875463f9cc96ab8
ERROR [2017-01-17 00:54:52,833] com.vmware.photon.controller.api.frontend.commands.BaseCommand: Command execution failed with exception
! com.vmware.photon.controller.api.frontend.exceptions.external.DeploymentFailedException: Deployment #aef065875463f9cc96ab8 failed: Container null of type Lightwave on VM 192.168.218.34 failed to become ready after 300 iterations
! at com.vmware.photon.controller.api.frontend.commands.steps.DeploymentStatusStepCmd$DeploymentStatusStepPoller.handleTaskFailure(DeploymentStatusStepCmd.java:176)
```

I sshed to lightwave VM and did `docker ps`. and I saw one container running `vmware/lightwave-sts:1.0.2`

 `docker logs {container_id}`  shows empty logs.

Not sure if it's important or not - Ligthwave VM doesn't have an internet access.

**Comment by snambakam** [comment]
The Lightwave Docker Container is setup using host networking. If you login to the Lightwave Container (docker exec -it <id of container> /bin/bash) and run "/opt/vmware/bin/domainjoin info", you should see that it is in domain controller mode. "systemctl status vmware-stsd" should indicate the service as running. The Photon Controller VM should be able to have network connectivity to the VM running Lightwave.

**Comment by medvedzver** [comment]
@snambakam Thanks for the answer!

`domainjoin info` shows nothing:  `Domain: `

`systemctl status vmware-stsd` shows 

![image](https://cloud.githubusercontent.com/assets/1127608/22213197/1e1f3c88-e148-11e6-84e4-03e97175d9ba.png)

Can you please tell me how to troubleshoot this? I can't find any useful logs.
`/var/log/lightwave` folder is empty.

**Comment by medvedzver** [comment]
I've run `/opt/vmware/sbin/vmware-stsd.sh start`  
Output says `SSO started successfully`. But it didn't. 
`systemctl status vmware-stsd` still shows `inactive`.

But now I have logs in `/var/log/vmware/sso/`. For some reason this folder was empty before.
Here is a content of `vmware-idmd.err`

![image](https://cloud.githubusercontent.com/assets/1127608/22214893/3eca43d2-e14e-11e6-9a06-9c523072d7a0.png)
