### ISSUE TITLE
Setting up of kubernetes cluster via photon controller  UI fails 

### ISSUE THREAD

**Issue by reachrkr** [vmware/photon-controller#88]
[photon-controller-log.zip](https://github.com/vmware/photon-controller/files/750593/photon-controller-log.zip)
Since this is a local workbench setup  below are the details 

Deployment ID: fcbb929b5479e91a4cd02
  State:                       READY

  Image Datastores:            [datastore1]
  Use image datastore for vms: true

  Syslog Endpoint:             -
  Ntp Endpoint:                -

  LoadBalancer:
    Enabled:                   true
    Address:                   192.168.209.35

  Auth:
    Enabled:                   false

  Stats:
    Enabled:               false

  Migration status:
    Completed data migration cycles:          0
    Current data migration cycles progress:   0 / 0
    VIB upload progress:                      0 / 0

  Cluster Configurations:
    ClusterConfiguration 1:
      Kind:      clusterConfig
      Type:      KUBERNETES
      ImageID:   d47ede8e-696b-4fa3-8953-ce0900f67d16

  Job                   VM IP(s)        Ports
  LoadBalancer          192.168.209.35  28080, 4343, 443, 80
  ManagementUi          192.168.209.35  20000, 20001
  PhotonControllerCore  192.168.209.35  19000, 9000

  VM IP           Host IP         VM ID                                 VM Name
  192.168.209.35  192.168.209.31  143e0ed4-50c5-4d97-a845-92ef1261c593  ec-mgmt-192-168-209-310d223

----------------------------------------------------------------------------------------------------------

! com.vmware.photon.controller.api.frontend.exceptions.external.TaskNotCompletedException: Step "StepEntity{id=null, kind=step, state=ERROR, operation=CREATE_KUBERNETES_CLUSTER_INITIATE, startedTime=Fri Feb 03 12:44:52 GMT 2017, queuedTime=Fri Feb 03 12:44:52 GMT 2017, endTime=Fri Feb 03 12:44:52 GMT 2017, sequence=0, error=StepErrorEntity{id=null, kind=step-error, code=SpecInvalid, message=Spec invalid:Invalid extended property: master ip:  203.0.113.208}}" did not complete.
! at com.vmware.photon.controller.api.frontend.commands.tasks.TaskCommand.execute(TaskCommand.java:118)
! at com.vmware.photon.controller.api.frontend.commands.BaseCommand.run(BaseCommand.java:58)
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
! at java.lang.Thread.run(Thread.java:745)
ERROR [2017-02-03 12:44:52,576] com.vmware.photon.controller.api.frontend.commands.tasks.TaskCommand: Task a5d083715479fa5e9e698 failed
! com.vmware.photon.controller.api.frontend.exceptions.external.TaskNotCompletedException: Step "StepEntity{id=null, kind=step, state=ERROR, operation=CREATE_KUBERNETES_CLUSTER_INITIATE, startedTime=Fri Feb 03 12:44:52 GMT 2017, queuedTime=Fri Feb 03 12:44:52 GMT 2017, endTime=Fri Feb 03 12:44:52 GMT 2017, sequence=0, error=StepErrorEntity{id=null, kind=step-error, code=SpecInvalid, message=Spec invalid:Invalid extended property: master ip:  203.0.113.208}}" did not complete.

**Comment by AlainRoy** [comment]
What do you mean by "local workbench setup"? What version is this, exactly?

**Comment by reachrkr** [comment]
Oops sorry I meant a vmware workstation setup , Have updated the details . I am using  controller version 1.1 Please do let me know if you need any more information .

**Comment by AlainRoy** [comment]
Is it possible to take a screenshot of how you made the Kubernetes cluster in the UI, so we can see exactly what parameters you provided?

Did you copy and paste the error about the invalid property, or retype it? If you copied and pasted it, then this looks suspiciously like a bug on our part, because it's missing an underscore in the name. 

As a workaround, you can definitely use the CLI.

**Comment by reachrkr** [comment]
Hi  Alain , 

I have copy pasted it  . I have already attached the logs  , you might want to have a look at it. Meanwhile , will  capture the screen shots and post them here

**Comment by reachrkr** [comment]
[screenshots.zip](https://github.com/vmware/photon-controller/files/751019/screenshots.zip)

**Comment by AlainRoy** [comment]
We have some code that validates that you gave a valid IP address. We're using an open source Apache package to do that. Apparently it thinks the ".0" in your master IP address is invalid. I have no idea why it thinks this--it's definitely valid. 

I can file a bug on this, but it may take a little while to get a fix for it. Is there any chance that you can use a subnet without a .0 in it?

**Comment by reachrkr** [comment]
Thanks Alain. Yeah i can try without  a .0 Well, I was just trying out the cluster create command line wiki example from UI .   Apparently I guess same issue can be relative with other IPv4 related fields also.

**Comment by AlainRoy** [comment]
Yes, we have this bug in a few places. I've filed a bug and we'll fix it ASAP. Certainly for our next release, 1.2.

**Comment by reachrkr** [comment]
Thanks Alain . Its very tough to work on UI , I get through strange errors like  "Spec invalid:Invalid extended property: dns: 203.2.113.1" Screen shot and logs attached .
[photon-controller-log.zip](https://github.com/vmware/photon-controller/files/760996/photon-controller-log.zip)
<img width="845" alt="2017-02-08 20_32_45" src="https://cloud.githubusercontent.com/assets/292926/22742888/64270b4a-ee3e-11e6-9546-09ce7a741565.png">
