### ISSUE TITLE
Photon Controller deployed with NSX-t failed : Generating certificate failed

### ISSUE THREAD

**Issue by roninby** [vmware/photon-controller#89]
I'm going to deploy Photon Controller 1.1 with NSX-t 1.1 together using 5 physical ESXi 6.0u2 (Build 4600944) hosts:

lab07:  NSX Components, Photon Controller Deployer
lab08:  Photon Controller, NSX Transport Node
lab09:  Lightwave & Cloud Node, NSX Transport Node
lab10: Cloud Node, NSX Transport Node
lab11: Cloud Node, NSX Transport Node

The configuration of NSX looks good as it's already tested to manually adding Transport Nodes via NSX Manager, and there was also no problem when deploying of Photon Controller/Lightwave without NSX.   But it stuck when making them together during the step 3 of the Photon Controller deployment right after Lightwave VM was created, the error message is below:

2017/02/11 23:39:19 Error: photon: Task 'b6432e55548429c325d0c' is in error state: {@step=={"sequence"=>"2","state"=>"ERROR","errors"=>[photon: { HTTP status: '0', code: 'DeploymentFailed', message: 'Deployment #b6432e55548429a3ff733 failed: Generating certificate failed with exit code 1', data: 'map[error:Generating certificate failed with exit code 1 id:b6432e55548429a3ff733]' }],"warnings"=>[],"operation"=>"PROVISION_CONTROL_PLANE_VMS","startedTime"=>"1486827109200","queuedTime"=>"1486825809144","endTime"=>"1486827559210","options"=>map[b6432e55548429a3ff733:deployment]}}
API Errors: [photon: { HTTP status: '0', code: 'DeploymentFailed', message: 'Deployment #b6432e55548429a3ff733 failed: Generating certificate failed with exit code 1', data: 'map[id:b6432e55548429a3ff733 error:Generating certificate failed with exit code 1]' }]

More details can be found in the attached photon-controller.log
[Uploading photon-controller.zip…]()

Pls help advise how to fix the certificate issue. Thanks.

Below is the yaml file for the deployment:
hosts:
  - address_ranges: 192.168.200.8
    username: root
    password: GCPS17@bj
    usage_tags:
      - MGMT
    metadata:
      MANAGEMENT_DATASTORE: DS-SAS300-Lab08
      MANAGEMENT_PORTGROUP: PG-Photon-Mgmt
      MANAGEMENT_NETWORK_NETMASK: 255.255.255.0
      MANAGEMENT_NETWORK_DNS_SERVER: 172.31.2.1
      MANAGEMENT_NETWORK_GATEWAY: 192.168.101.254
      MANAGEMENT_VM_IPS: 192.168.101.12
  - address_ranges: 192.168.200.9
    username: root
    password: GCPS17@bj
    usage_tags:
      - MGMT
      - CLOUD
    metadata:
      MANAGEMENT_DATASTORE: DS-SAS300-Lab09
      MANAGEMENT_PORTGROUP: PG-Photon-Mgmt
      MANAGEMENT_NETWORK_NETMASK: 255.255.255.0
      MANAGEMENT_NETWORK_DNS_SERVER: 172.31.2.1
      MANAGEMENT_NETWORK_GATEWAY: 192.168.101.254
      ALLOWED_SERVICES: Lightwave
      MANAGEMENT_VM_IPS: 192.168.101.13
  - address_ranges: 192.168.200.10-192.168.200.11
    username: root
    password: GCPS17@bj
    usage_tags:
      - CLOUD
deployment:
  resume_system: true
  image_datastores:
    - DS-SAS300-Lab08
    - DS-SAS300-Lab09
  auth_enabled: true
  sdn_enabled: true
  network_manager_address: 192.168.101.1
  network_manager_username: admin
  network_manager_password: GCPS17@bj
  network_top_router_id: e3db6c66-4f15-481b-8b24-acd976940d04
  network_zone_id: d8e5dde5-0750-46cf-ac8f-5115209af475
  network_edge_ip_pool_id: 99c45c8f-9709-49b4-909a-a5c41659d4e4
  network_host_uplink_pnic: vmnic2
  network_ip_range: 10.10.102.0/24
  network_external_ip_range: 172.31.4.11-172.31.4.199
  network_dhcp_servers:
  - 172.31.4.1
  stats_enabled: false
  ntp_endpoint: 172.31.1.1
  use_image_datastore_for_vms: true
  loadbalancer_enabled: true
  oauth_username: 'Administrator'
  oauth_tenant: 'esxcloud'
  oauth_password: 'GCPS17@bj'
  oauth_security_groups:
    - "esxcloud\\Administrators"
    - "esxcloud\\photonControllerAdmins"

**Comment by roninby** [comment]
The log is uploaded again.
[photon-controller.zip](https://github.com/vmware/photon-controller/files/768739/photon-controller.zip)

**Comment by roninby** [comment]
From the log, it looks like there's something wrong with the keystore. Is there any advise on this? Thanks.

INFO  [2017-02-11 15:38:47,999] com.vmware.photon.controller.deployer.xenon.workflow.BatchCreateManagementWorkflowService: [/photon/workflow/batch-create-mgmt-vm/b6432e5554842e98d72f4] Handling patch for service /photon/workflow/batch-create-mgmt-vm/b6432e5554842e98d72f4
INFO  [2017-02-11 15:38:47,999] com.vmware.photon.controller.deployer.xenon.workflow.BatchCreateManagementWorkflowService: [/photon/workflow/batch-create-mgmt-vm/b6432e5554842e98d72f4] Moving to stage STARTED:REGISTER_AUTH_CLIENT_FOR_SWAGGER_UI
INFO  [2017-02-11 15:38:47,999] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e555484302a60e22] Starting service /photon/register-auth-tasks/b6432e555484302a60e22
INFO  [2017-02-11 15:38:47,999] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e555484302a60e22] Sending stage progress path STARTED
INFO  [2017-02-11 15:38:48,001] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e555484302a60e22] Handling patch for service /photon/register-auth-tasks/b6432e555484302a60e22
INFO  [2017-02-11 15:38:48,006] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e555484302a60e22] Query from service /photon/register-auth-tasks/b6432e555484302a60e22 returned 1 results
  - /photon/container-templates/b6432e55548429c32b6f2
INFO  [2017-02-11 15:38:48,007] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e555484302a60e22] Query from service /photon/register-auth-tasks/b6432e555484302a60e22 returned 1 results
  - /photon/containers/b6432e55548429c562536
INFO  [2017-02-11 15:38:48,007] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e555484302a60e22] Starting a thread to register client 192.168.101.12 at 192.168.101.13:443 using user administrator on tenant esxcloud.
INFO  [2017-02-11 15:39:12,839] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e555484302a60e22] Handling patch for service /photon/register-auth-tasks/b6432e555484302a60e22
INFO  [2017-02-11 15:39:12,841] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e555484302a60e22] Query from service /photon/register-auth-tasks/b6432e555484302a60e22 returned 1 results
  - /photon/container-templates/b6432e55548429c32b6f2
INFO  [2017-02-11 15:39:12,843] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e555484302a60e22] Query from service /photon/register-auth-tasks/b6432e555484302a60e22 returned 1 results
  - /photon/containers/b6432e55548429c562536
INFO  [2017-02-11 15:39:12,844] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e555484302a60e22] Starting a thread to register client 192.168.101.12 at 192.168.101.13:443 using user administrator on tenant esxcloud.
INFO  [2017-02-11 15:39:13,637] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e555484302a60e22] Handling patch for service /photon/register-auth-tasks/b6432e555484302a60e22
INFO  [2017-02-11 15:39:13,637] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e555484302a60e22] Moving to stage FINISHED
INFO  [2017-02-11 15:39:14,669] com.vmware.photon.controller.cloudstore.xenon.entity.DeploymentService: [/photon/cloudstore/deployments/b6432e55548429a3ff733] Handling patch for service /photon/cloudstore/deployments/b6432e55548429a3ff733
INFO  [2017-02-11 15:39:14,670] com.vmware.photon.controller.deployer.xenon.workflow.BatchCreateManagementWorkflowService: [/photon/workflow/batch-create-mgmt-vm/b6432e5554842e98d72f4] Handling patch for service /photon/workflow/batch-create-mgmt-vm/b6432e5554842e98d72f4
INFO  [2017-02-11 15:39:14,670] com.vmware.photon.controller.deployer.xenon.workflow.BatchCreateManagementWorkflowService: [/photon/workflow/batch-create-mgmt-vm/b6432e5554842e98d72f4] Moving to stage STARTED:REGISTER_AUTH_CLIENT_FOR_MGMT_UI
INFO  [2017-02-11 15:39:14,670] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e5554843043d05be] Starting service /photon/register-auth-tasks/b6432e5554843043d05be
INFO  [2017-02-11 15:39:14,670] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e5554843043d05be] Sending stage progress path STARTED
INFO  [2017-02-11 15:39:14,672] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e5554843043d05be] Handling patch for service /photon/register-auth-tasks/b6432e5554843043d05be
INFO  [2017-02-11 15:39:14,676] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e5554843043d05be] Query from service /photon/register-auth-tasks/b6432e5554843043d05be returned 1 results
  - /photon/container-templates/b6432e55548429c32b6f2
INFO  [2017-02-11 15:39:14,677] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e5554843043d05be] Query from service /photon/register-auth-tasks/b6432e5554843043d05be returned 1 results
  - /photon/containers/b6432e55548429c562536
INFO  [2017-02-11 15:39:14,677] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e5554843043d05be] Starting a thread to register client 192.168.101.12 at 192.168.101.13:443 using user administrator on tenant esxcloud.
INFO  [2017-02-11 15:39:15,441] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e5554843043d05be] Handling patch for service /photon/register-auth-tasks/b6432e5554843043d05be
INFO  [2017-02-11 15:39:15,441] com.vmware.photon.controller.deployer.xenon.task.RegisterAuthClientTaskService: [/photon/register-auth-tasks/b6432e5554843043d05be] Moving to stage FINISHED
INFO  [2017-02-11 15:39:16,609] com.vmware.photon.controller.cloudstore.xenon.entity.DeploymentService: [/photon/cloudstore/deployments/b6432e55548429a3ff733] Handling patch for service /photon/cloudstore/deployments/b6432e55548429a3ff733
INFO  [2017-02-11 15:39:16,634] com.vmware.photon.controller.deployer.xenon.workflow.BatchCreateManagementWorkflowService: [/photon/workflow/batch-create-mgmt-vm/b6432e5554842e98d72f4] Handling patch for service /photon/workflow/batch-create-mgmt-vm/b6432e5554842e98d72f4
INFO  [2017-02-11 15:39:16,635] com.vmware.photon.controller.deployer.xenon.workflow.BatchCreateManagementWorkflowService: **[/photon/workflow/batch-create-mgmt-vm/b6432e5554842e98d72f4] Moving to stage STARTED:GENERATE_CERT
ERROR [2017-02-11 15:39:17,129] com.vmware.photon.controller.deployer.xenon.workflow.BatchCreateManagementWorkflowService: [/photon/workflow/batch-create-mgmt-vm/b6432e5554842e98d72f4] generate-certificate returned 1
ERROR [2017-02-11 15:39:17,129] com.vmware.photon.controller.deployer.xenon.workflow.BatchCreateManagementWorkflowService: [/photon/workflow/batch-create-mgmt-vm/b6432e5554842e98d72f4] Script output: keytool error: java.io.IOException: Keystore was tampered with, or password was incorrect
keytool error: java.io.IOException: Keystore was tampered with, or password was incorrect
keytool error: java.io.IOException: Keystore was tampered with, or password was incorrect**

ERROR [2017-02-11 15:39:17,129] com.vmware.photon.controller.deployer.xenon.workflow.BatchCreateManagementWorkflowService: [/photon/workflow/batch-create-mgmt-vm/b6432e5554842e98d72f4] java.lang.IllegalStateException: Generating certificate failed with exit code 1
	at com.vmware.photon.controller.deployer.xenon.workflow.BatchCreateManagementWorkflowService.logScriptErrorAndFail(BatchCreateManagementWorkflowService.java:1242)
	at com.vmware.photon.controller.deployer.xenon.workflow.BatchCreateManagementWorkflowService.access$000(BatchCreateManagementWorkflowService.java:105)
	at com.vmware.photon.controller.deployer.xenon.workflow.BatchCreateManagementWorkflowService$1.onSuccess(BatchCreateManagementWorkflowService.java:776)
	at com.vmware.photon.controller.deployer.xenon.workflow.BatchCreateManagementWorkflowService$1.onSuccess(BatchCreateManagementWorkflowService.java:771)
	at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
	at com.google.common.util.concurrent.ListenableFutureTask.done(ListenableFutureTask.java:91)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384)
	at java.util.concurrent.FutureTask.set(FutureTask.java:233)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by roninby** [comment]
To make it totally clean, I just redeployed the Photon Controller Installer VM, then Photon Controller and Lightwave were successfully deployed afterwards.
However, there's still a network problem blocking the deployment of Kubernetes cluster later...


I created an On-demand network, and made it the default network in kub-project: 

[root@pc-ovftool tmp]# photon network create --name "net-103" --description "10.10.103.0" --routingType ROUTED --size 256 --staticIpSize 128 --projectId 8758ddef5489cb153de7f

[root@pc-ovftool tmp]# photon network show 8758ddef5489cc76c0321
Network ID: 8758ddef5489cc76c0321
  Name:             net-103
  State:            READY
  Description:      10.10.103.0
  Routing Type:     ROUTED
  Is Default:       %!s(bool=true)
  CIDR:             10.10.103.0/24
  Start Dynamic IP: 10.10.103.132
  End Dynamic IP:   10.10.103.254
  Start Static IP:  10.10.103.4
  End Static IP:    10.10.103.131
  Reserved IP List: [10.10.103.2 10.10.103.3 10.10.103.1]


Then I created a Kubernetes cluster, but found it's pending in "CREATING" for hours:

[root@pc-ovftool tmp]# photon cluster create -n kub-cluster -k KUBERNETES --master-ip 10.10.103.11 --etcd1 10.10.103.12 --container-network 10.199.199.0/24 --dns 10.10.103.13 --gateway 10.10.103.1 --netmask 255.255.255.0 -c 1 --vm_flavor cluster-small


[root@pc-ovftool tmp]# photon cluster show 3f2bed15-2986-41b1-a995-342be82dd04e
Cluster ID:             3f2bed15-2986-41b1-a995-342be82dd04e
  Name:                 kub-cluster2
  State:                CREATING
  Type:                 KUBERNETES
  Worker count:         1
  Extended Properties:  map[container_network:10.199.199.0/24 netmask:255.255.255.0 dns:10.10.103.23 etcd_ips:10.10.103.22 master_ip:10.10.103.21 gateway:10.10.103.1]

VM ID                                 VM Name                                    VM IP
bdd3ad31-e070-449d-bf2f-50b2cd5d4a24  etcd-da970b90-0eda-4cee-91a5-767e401ed735  10.10.103.22




From the photon controller log, it looks like Photon Controller (with IP 192.168.101.11 outside NSX) is requesting the status of the Etcd (with internal IP 10.10.101.22). Is that the cause of Etcd call fail?

As I know, the On-Demand network 10.10.132.0/24 can go outside with a SNAT rules in NSX, but not on the contrary. Is it required to connect Photon Controller to inside VMs like Etcd?

Thanks.

Photon-controller.log:
INFO  [2017-02-16 09:52:59,309] com.vmware.photon.controller.api.frontend.auth.AuthFilter: Allow: API call: info
INFO  [2017-02-16 09:52:59,329] com.vmware.photon.controller.api.frontend.auth.AuthFilter: Allow: API call: subnets/8758ddef5489cc76c0321
INFO  [2017-02-16 09:53:21,917] com.vmware.photon.controller.common.clients.HostClient: get_host_config target 192.168.200.8, request GetConfigRequest()
INFO  [2017-02-16 09:53:21,947] com.vmware.photon.controller.common.clients.HostClient: Checking GetConfigResponse(result:OK, hostConfig:HostConfig(agent_id:ca57d3065489ac9016ab0, datastores:[Datastore(id:589b5733-83f09221-af00-c81f66be0e57, name:DS-SAS300-Lab08, type:SHARED_VMFS, tags:[SHARED_VMFS]), Datastore(id:58a54d2c-739e80a5-f81e-c81f66be0e57, name:DS-SSD-Lab08, type:LOCAL_VMFS, tags:[LOCAL_VMFS])], address:ServerAddress(host:192.168.200.8, port:8835), networks:[Network(id:PG-Photon-Mgmt, types:[VM]), Network(id:VM Network, types:[VM]), Network(id:PC-LogicalSwitch-8758ddef5489cc76c0321, types:[VM]), Network(id:ls-10.10.101, types:[VM]), Network(id:ls-10.10.102, types:[VM])], management_only:true, image_datastore_ids:[589b5733-83f09221-af00-c81f66be0e57], memory_mb:65490, cpu_count:32, esx_version:6.0.0, deployment_id:ca57d3065489ac8f85678))
INFO  [2017-02-16 09:53:21,947] com.vmware.photon.controller.cloudstore.xenon.entity.HostService: [/photon/cloudstore/hosts/ca57d3065489ac9016ab0] Patching service /photon/cloudstore/hosts/ca57d3065489ac9016ab0
INFO  [2017-02-16 09:53:21,948] com.vmware.photon.controller.cloudstore.xenon.entity.DatastoreService: [/photon/cloudstore/datastores/589b5733-83f09221-af00-c81f66be0e57] Handling put for service /photon/cloudstore/datastores/589b5733-83f09221-af00-c81f66be0e57
INFO  [2017-02-16 09:53:21,948] com.vmware.photon.controller.cloudstore.xenon.entity.DatastoreService: [/photon/cloudstore/datastores/58a54d2c-739e80a5-f81e-c81f66be0e57] Handling put for service /photon/cloudstore/datastores/58a54d2c-739e80a5-f81e-c81f66be0e57
WARN  [2017-02-16 09:53:33,733] com.vmware.photon.controller.clustermanager.statuschecks.EtcdStatusChecker: Etcd call failed:
! java.net.ConnectException: Connection timed out
! at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
! at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
! at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:173)
! at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:147)
! at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
! at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:189)
! at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.doExecute(CloseableHttpAsyncClientBase.java:67)
! at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.access$000(CloseableHttpAsyncClientBase.java:38)
! at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:57)
! at java.lang.Thread.run(Thread.java:745)
INFO  [2017-02-16 09:53:38,733] com.vmware.photon.controller.clustermanager.tasks.ClusterWaitTaskService: [/photon/clustermanager/wait-for-cluster-tasks/8758ddef548a0ea740ad1] Handling patch operation for service /photon/clustermanager/wait-for-cluster-tasks/8758ddef548a0ea740ad1
INFO  [2017-02-16 09:53:38,733] com.vmware.photon.controller.clustermanager.statuschecks.EtcdStatusChecker: Checking Etcd: 10.10.103.22
WARN  [2017-02-16 09:54:18,405] com.vmware.photon.controller.clustermanager.statuschecks.EtcdStatusChecker: Etcd call failed:
! java.net.ConnectException: Connection timed out
! at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
! at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
! at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:173)
! at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:147)
! at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
! at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:189)
! at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.doExecute(CloseableHttpAsyncClientBase.java:67)
! at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.access$000(CloseableHttpAsyncClientBase.java:38)
! at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:57)
! at java.lang.Thread.run(Thread.java:745)
