### ISSUE TITLE
Photon Controller 1.1.1 ERROR Error: Failed to install Lightwave java.lang.NullPointerException

### ISSUE THREAD

**Issue by alancivita** [vmware/photon-controller#95]
Hello, i,m trying to isntall PC 1.1.1 but i get this error while deploying Lightwave:
2017-03-06 10:58:37 INFO  Installing Lightwave
2017-03-06 10:58:37 INFO  Install Lightwave Controller at lightwave-1
2017-03-06 10:58:41 INFO  Info: Lightwave was not existing at the specified at the given IP address.Deploying new Lightwave OVA
2017-03-06 10:58:41 INFO  Start [Task: Lightwave Installation]
2017-03-06 10:58:42 INFO  Stop [Task: Lightwave Installation]
2017-03-06 10:58:42 ERROR Error: Failed to install Lightwave
java.lang.NullPointerException
	at com.vmware.photon.platform.setup.installer.LightwaveInstaller.install(LightwaveInstaller.java:136)
	at com.vmware.photon.platform.setup.installer.PhotonSetupImpl.InstallLightwave(PhotonSetupImpl.java:50)
	at com.vmware.photon.platform.setup.PlatformInstaller.InstallLightwave(PlatformInstaller.java:102)
	at com.vmware.photon.platform.setup.PlatformInstaller.install(PlatformInstaller.java:71)
	at com.vmware.photon.platform.setup.PhotonSetup.main(PhotonSetup.java:47)
com.vmware.photon.platform.setup.installer.InstallException: Error: Failed to install Lightwave

any tips?
esx version is Version: 6.0.0 Update 2 (Build 4600944)
attached config.yml used for the setup, photon-installer logs and the output of the setup command
just some notes:
i have 4 esx hosts (2 will be used for PC and Lightwave) and 2 as Compute/Cloud resources.
Only local datastores will be used.

Thanks
[config.yml.txt](https://github.com/vmware/photon-controller/files/820914/config.yml.txt)
[setup.out.txt](https://github.com/vmware/photon-controller/files/820915/setup.out.txt)
[photon-installer.log.txt](https://github.com/vmware/photon-controller/files/820916/photon-installer.log.txt)

**Comment by mwest44** [comment]
Can you verify that you have connectivity from the installer VM to host 10.90.44.56 and that the credentials are correct.   Can you share the entire photon-installer.log file.

Also, note in your yml, the dns for the controllers needs to be the Lightwave VM IP.

**Comment by alancivita** [comment]
Thanks, i've corrected the DNS part..and rerun the setup but still getting the  same error:
this is the content of photon-installer log:
cat /var/log/photon-installer.log
2017-03-06 11:57:50 DEBUG IdentityConfig:113 - Debug: Domain name is validated succesfully
2017-03-06 11:57:50 DEBUG IdentityConfig:127 - Debug: The lightwave instance has an Administrator User
2017-03-06 11:57:50 INFO  PlatformInstaller:92 - Installing Lightwave
2017-03-06 11:57:50 INFO  PlatformInstaller:100 - Install Lightwave Controller at lightwave-1
2017-03-06 11:57:50 DEBUG LightwaveController:108 - Info: Checking Lightwave at 10.90.44.56
2017-03-06 11:57:54 INFO  PhotonSetupImpl:42 - Info: Lightwave was not existing at the specified at the given IP address.Deploying new Lightwave OVA
2017-03-06 11:57:54 INFO  TaskReporter:19 - Start [Task: Lightwave Installation]
2017-03-06 11:57:54 INFO  TaskReporter:44 - Stop [Task: Lightwave Installation]
2017-03-06 11:57:54 ERROR PhotonSetupImpl:55 - Error: Failed to install Lightwave
java.lang.NullPointerException
	at com.vmware.photon.platform.setup.installer.LightwaveInstaller.install(LightwaveInstaller.java:136)
	at com.vmware.photon.platform.setup.installer.PhotonSetupImpl.InstallLightwave(PhotonSetupImpl.java:50)
	at com.vmware.photon.platform.setup.PlatformInstaller.InstallLightwave(PlatformInstaller.java:102)
	at com.vmware.photon.platform.setup.PlatformInstaller.install(PlatformInstaller.java:71)
	at com.vmware.photon.platform.setup.PhotonSetup.main(PhotonSetup.java:47)


Is it mandatory to deploy the Installer with  a "VM Network" portgroup?

**Comment by alancivita** [comment]
I can't test the connection to 10.90.44.56, because it is the Lightwave ip address, but LW is not deployed yet

**Comment by mwest44** [comment]
sorry i meant the host IP:   10.90.233.196

**Comment by alancivita** [comment]
yes sure, just ssh into it from the installer.
i'd like to mention that these hosts were hosting the Photon controller 1.1.0 installation..but last week i've destroyed the deployment, removed photon-controller, lightwave and envoy vibs, cleaned everything...if this can help

**Comment by mwest44** [comment]
this is new enough that I haven't tried every combination of config yet.  I use an FQDN for the hostname.  If we are trying to connect via your hostname, will it resolve to the correct IP?

You might try connecting to the host via ip and your hostname:  hdesx42d
if that doesn't work, then you might add entries to /etc/hosts on the installer for your esxi hosts

**Comment by alancivita** [comment]
i've added the hosts entires in /etc/hosts, but still same error.
will check better after lunch 
many thanks

**Comment by mwest44** [comment]
ok.  if you will send me the complete log from /var/log/photon-installer.log I might have some other ideas.

**Comment by alancivita** [comment]
Attached the photon-installer.log 
[photon-installer.log.txt](https://github.com/vmware/photon-controller/files/821668/photon-installer.log.txt)

**Comment by alancivita** [comment]
quick update:
if i try to deploy only the controller i get this error:
/opt/vmware/photon/controller/bin/photon-setup controller install -config /tmp/config.yml
Using configuration at /tmp/config.yml
INFO: Parsing Lightwave Configuration
INFO: Parsing Credentials
INFO: Lightwave Credentials parsed successfully
INFO: Parsing Lightwave Controller Config
INFO: Parsing appliance
INFO: Parsing Credentials
INFO: Appliance Credentials parsed successfully
INFO: Parsing Network Config
INFO: Appliance network config parsed successfully
INFO: Appliance config parsed successfully
INFO: Lightwave Controller parsed successfully
INFO: Lightwave Controller config parsed successfully
INFO: Lightwave Section parsed successfully
INFO: Parsing Photon Controller Configuration
INFO: Parsing Photon Controller Image Store
INFO: Image Store parsed successfully
INFO: Managed hosts parsed successfully
INFO: Parsing Photon Controller Config
INFO: Parsing appliance
INFO: Parsing Credentials
INFO: Appliance Credentials parsed successfully
INFO: Parsing Network Config
INFO: Appliance network config parsed successfully
INFO: Photon Controllers parsed successfully
INFO: Photon section parsed successfully
INFO: Parsing Compute Configuration
INFO: Parsing Compute Config
INFO: Parsing Credentials
INFO: Parsing Credentials
INFO: Parsing Credentials
INFO: Parsing Credentials
INFO: Compute Config parsed successfully
INFO: Parsing LoadBalancer Configuration
INFO: Parsing LoadBalancer Config
INFO: Parsing appliance
INFO: Parsing Credentials
INFO: Appliance Credentials parsed successfully
INFO: Parsing Network Config
INFO: Appliance network config parsed successfully
INFO: LoadBalancer Config parsed successfully
com.vmware.photon.platform.setup.installer.config.ConfigException: Error: Failed to find hypervisor hdesx42c.mydomain.com for Photon Controller node

from the installer i can resolve and ping hdesx42c.mydomain.com as well as all the other hypervisors

**Comment by mwest44** [comment]
I just downloaded this build from the releases page and was able to install it successfully.
It seems you are failing either just before or during the ovf deploy of the lightwave vm.
That usually means esxi credentials or some issue with network or name resolution.  I will check with the engineer as soon as he gets in.

This is the first line that is different in your log file from mine:  2017-03-06 15:57:31 INFO  TaskReporter:44 - Stop [Task: Lightwave Installation]

My shows TaskReporter:39.       Not sure what we are doing here, but will update shortly

**Comment by alancivita** [comment]
Thanks for the effort! i will try top redeploy again and let you know

**Comment by AlainRoy** [comment]
I looked at the YAML file you posted at the beginning (not sure if you changed it since) and I think I see a problem. It's the same mistake I made when I first installed--we need to add validation to the installer to catch this one. 

Look at this portion:

```
compute:
  hypervisors:
    esxi-42c:
      hostname: "hdesx42c"
      ipaddress: "10.90.233.195"
      dns: "10.90.44.56"
```

Then look at this portion that refers to it:
```
loadBalancer:
  load-balancer-1:
    appliance:
      hostref: "hdesx42c"
```

The hostref should not be the hostname, but should be `esxi-42c`. (It should be in quotes, as you have it.)

It's not just the loadbalancer, but other places you need to do this. 

Also, I saw something that, while it may not cause a problem, will be ignored. I'm not certain though. It's this:
```
photon:
  imagestore:
    img-store-1:
      hostref: "hdesx42c, hdesx42d, hdesx42e, hdesx42f"
      datastore: "datastore42c, datastore42d, datastore42e, datastore42f"
      enableimagestoreforvms: "true"
```
Specifically, it's the `hostref` under `img-store-1`.  I think that field is ignored. The `datastore` and `enableimagestoreformvs` are used.  I'm not 100% certain about this though.

**Comment by mwest44** [comment]
Nice catch Alain.  :)

**Comment by alancivita** [comment]
bloody yaml :) i will give it a go later thanks!

**Comment by alancivita** [comment]
That fixed the issue! brilliant thanks Michael and Alain!

**Comment by AlainRoy** [comment]
Excellent, glad to hear it! We need to add validation that catches this for you--we'll work on that.

**Comment by alancivita** [comment]
or just the example in docs :)

**Comment by rushins** [comment]
i am getting this even after making the fixes you guys mentioned

-----
2017-07-17 20:12:19 ERROR Error: Failed to install Controller Cluster
com.vmware.photon.platform.setup.installer.InstallException: The PC node at 10.48.185.133 failed to provide correct status after 300 iterations
       	at com.vmware.photon.platform.setup.installer.ControllerClusterInstaller.checkPhotonStatus(ControllerClusterInstaller.java:262)
       	at com.vmware.photon.platform.setup.installer.ControllerClusterInstaller.install(ControllerClusterInstaller.java:165)
       	at com.vmware.photon.platform.setup.installer.PhotonSetupImpl.InstallPhotonControllerCluster(PhotonSetupImpl.java:87)
       	at com.vmware.photon.platform.setup.PlatformInstaller.InstallPhoton(PlatformInstaller.java:143)
       	at com.vmware.photon.platform.setup.PlatformInstaller.install(PlatformInstaller.java:73)
       	at com.vmware.photon.platform.setup.PhotonSetup.main(PhotonSetup.java:47)
com.vmware.photon.platform.setup.installer.InstallException: Error: Failed to install Controller Cluster
------
